
//!!!!!!!!!!!!!!!!!!!!!!!ACHTUNG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//wenn die Datei geändert wird unbedingt auch config.h von Projekt "FabianInstaller" und "Fabian" nachziehen
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

enum eAcuLinkVersion {
	ALINKVERS_3		= 0,
	ALINKVERS_4		= 1
};

enum eDevType {
	DEV_EVO		= 0,
	DEV_THERAPY	= 1,
	DEV_HFO		= 2
};

enum eFlowSensorType {
	FSENS_NEONATAL		= 0,
	FSENS_PEDIATRIC		= 1
};

enum eAVRevision {
	AVREV_1		= 0,
	AVREV_4		= 1
};

enum eHFModuleRevision {
	HFREV_1		= 0,
	HFREV_2		= 1
};

#define DEMOLICENSE	90


//#define MAINBOARD2_1			0x21
//#define MAINBOARD3_0			0x30
#define MAINBOARD_11			0x11
#define MAINBOARD_12			0x12
#define MAINBOARD_13			0x13
#define MAINBOARD_20			0x20
#define MAINBOARD_21			0x21
#define MAINBOARD_21			0x22
#define MAINBOARD_30			0x30
#define MAINBOARD_31			0x31
#define MAINBOARD_32			0x32
#define MAINBOARD_33			0x33
#define MAINBOARD_40			0x40

#define SERIAL_COM1				0x01
#define SERIAL_COM2				0x02

#define CO2MODULE_NONE			0x00
#define CO2MODULE_CAPNOSTAT		0x01
#define CO2MODULE_MICROPOD		0x02
#define CO2MODULE_SENTEC		0x03

#define SPO2MODULE_NONE			0x00
#define SPO2MODULE_MASIMO		0x01


#define COMMODULE_NONE			0x00
#define COMMODULE_INBIOLAB		0x01
//#define NOPDMS					0x00
//#define ACULINK					0x01
//#define VUELINK					0x02

#define ACL_NOPDMS			0
#define ACL_SERIAL_ASCII	1
#define ACL_SERIAL_IVOI		2
#define ACL_ETHERNET		3
#define ACL_TERMINAL		4
#define ACL_SERIAL_WAVE		5
#define ACL_ETHERNET_WAVE	6
//new eigenes protocol
#define ACL_RS232_IVOI		7
#define ACL_RS232_DATA		8
#define ACL_RS232_WAVES		9
#define ACL_RJ45_DATA		10
#define ACL_RJ45_WAVES		11

//language IDs
enum eLanguage {
	LAN_ENGLISH,		// 0,
	LAN_GERMAN,			// 1, 
	LAN_RUSSIAN,		// 2,
	LAN_FRENCH,			// 3, 
	LAN_ITALIAN,		// 4,
	LAN_FINNISH,		// 5,	
	LAN_SPANISH,		// 6,
	LAN_PORTUGUESE,		// 7,
	LAN_SLOVENSKO,		// 8,
	LAN_CZECH,			// 9,
	LAN_SWEDISH,		// 10
	LAN_DUTCH,			// 11
	LAN_POLISH,			// 12
	LAN_CHINESE,		// 13
	LAN_JAPANESE,		// 14
	LAN_TURKISH,		// 15
	LAN_AMERICAN,		// 16
	LAN_NORWAY,			// 17
	LAN_HUNGARIAN,		// 18
	LAN_DANSK			// 19
};

//Alarmgrenzen AUTO
#define	AUTOALARMLIMIT_MVMAX		180		//!< MV max: 80% above measured MV
#define	AUTOALARMLIMIT_MVMIN		50		//!< MV min: 50% below measured MV
#define	AUTOALARMLIMIT_DCO2MAX	150		//!< DCO2 max: 50% above measured DCO2 
#define	AUTOALARMLIMIT_DCO2MIN	50		//!< DCO2 min: 50% below measured DCO2 
#define	AUTOALARMLIMIT_ETCO2MAX	150		//!< ETCO2 max: 50% above measured ETCO2 
#define	AUTOALARMLIMIT_ETCO2MIN	50		//!< ETCO2 min: 50% below measured ETCO2 
#define	AUTOALARMLIMIT_FICO2MAX	150		//!< FICO2 max: 50% above measured FICO2 
#define	AUTOALARMLIMIT_FICO2MIN	50		//!< FICO2 min: 50% below measured FICO2 

#define	AUTOALARMLIMIT_SPO2MAX	150		//!< SPO2 max: 50% above measured SPO2 
#define	AUTOALARMLIMIT_SPO2MIN	50		//!< SPO2 min: 50% below measured SPO2
#define	AUTOALARMLIMIT_PULSERATEMAX	150		//!< PULSERATE max: 50% above measured PulseRate 
#define	AUTOALARMLIMIT_PULSERATEMIN	50		//!< PULSERATE min: 50% below measured PulseRate
#define	AUTOALARMLIMIT_SPO2_PIMIN	50		//!< PERFUSIONINDEX min: 50% below measured PI
#define AUTOALARMLIMIT_SPO2_SIQMIN	30		//!< SIGNAL OF QUALITY min: 30

#define	AUTOALARMLIMIT_VLIMIT		130		//!< Volumenlimit (max): 30% above measured Atemzugvolumen
#define	AUTOALARMLIMIT_LEAK			150		//!< Leak (max): 50% above measured  tubus leak up to maximum value off 50% tubus leak
#define	AUTOALARMLIMIT_LEAKMAX		50		//!< maximum value off 50% tubus leak
#define	AUTOALARMLIMIT_LEAKMIN		10		//!< maximum value off 8% tubus leak
#define	AUTOALARMLIMIT_BPM			150		//!< BPM (max): 50% above measured frequency
#define	AUTOALARMLIMIT_APNOE		10		//!< APNOE (max): 10sec
#define	AUTOALARMLIMIT_PIPMAX		50		//!< Pmax: 5 mbar above setting off PIP
#define	AUTOALARMLIMIT_PIPMIN		20		//!< Pmax: 2 mbar über PEEP limit
#define	AUTOALARMLIMIT_PMAXHFO		50		//!< Pmax: 5 mbar above measured Inspirationsdruck
#define	AUTOALARMLIMIT_PEEP			30		//!< PEEP (Pmin): 3 mbar below setting off PEEP
#define	AUTOALARMLIMIT_CPAP			50		//!< CPAP (Pmin): 5 mbar below/above setting off CPAP
#define	AUTOALARMLIMIT_NCPAP		20		//!< NCPAP (Pmin): 2 mbar below setting off  CPAP
#define	AUTOALARMLIMIT_DUOPAP		20		//!< NCPAP (Pmin): 2 mbar below setting off  CPAP
#define AUTOALARMLIMIT_MAPMAX		50		//!< MAPmax: 5 mbar above setting off Pmean
#define AUTOALARMLIMIT_MAPMIN		50		//!< MAPmin: 5 mbar below setting off Pmean

//ALARMLIMITS
#define DIFF_PMAX_PMIN_LIMIT			10
#define DIFF_PMIN_PMAX_LIMIT			5

#define DIFF_MAPMAX_MAPMIN_LIMIT		10

#define MAXRANGE_NEONATAL_MVMAX			7000
#define MINRANGE_NEONATAL_MVMIN			10//rku MVLOW
#define MAXRANGE_NEONATAL_PMAX			900
#define MAXRANGE_NEONATAL_CPAPPEEPMAX	400
#define MINRANGE_NEONATAL_CPAPPEEPMIN	-100

#define MAXRANGE_NEONATAL_NMODEMAX		300//200
#define MINRANGE_NEONATAL_NMODEPEEPMIN	-50

#define MAXRANGE_NEONATAL_BPMMAX		220
#define MINRANGE_NEONATAL_BPMMIN		10
#define MAXRANGE_NEONATAL_LEAKMAX		50
#define MINRANGE_NEONATAL_LEAKMIN		10
#define MAXRANGE_NEONATAL_APNOE			20
#define MINRANGE_NEONATAL_APNOE			2
#define MAXRANGE_NEONATAL_ETCO2MAX		1490
#define MINRANGE_NEONATAL_ETCO2MIN		10

#define MAXRANGE_NEONATAL_FICO2MAX		1490
#define MINRANGE_NEONATAL_FICO2MIN		10

#define MAXRANGE_NEONATAL_SPO2MAX		1000//990	
#define MINRANGE_NEONATAL_SPO2MIN		0//10
#define MAXRANGE_NEONATAL_PULSERATEMAX	235
#define MINRANGE_NEONATAL_PULSERATEMIN	30
#define MAXRANGE_NEONATAL_SPO2_PIMIN	19000
#define MINRANGE_NEONATAL_SPO2_PIMIN	30
#define MAXRANGE_NEONATAL_SPO2_SIQMIN	100
#define MINRANGE_NEONATAL_SPO2_SIQMIN	0

#define MAXRANGE_PEDIATRIC_MVMAX		10000
#define MINRANGE_PEDIATRIC_MVMIN		10//rku MVLOW
#define MAXRANGE_PEDIATRIC_PMAX			900

#define MAXRANGE_PEDIATRIC_CPAPPEEPMAX	400
#define MINRANGE_PEDIATRIC_CPAPPEEPMIN	-100

#define MAXRANGE_PEDIATRIC_NMODEMAX		300//200
#define MINRANGE_PEDIATRIC_NMODEPEEPMIN	-50

#define MAXRANGE_PEDIATRIC_BPMMAX		220
#define MINRANGE_PEDIATRIC_BPMMIN		10
#define MAXRANGE_PEDIATRIC_LEAKMAX		50
#define MINRANGE_PEDIATRIC_LEAKMIN		10
#define MAXRANGE_PEDIATRIC_APNOE		20
#define MINRANGE_PEDIATRIC_APNOE		2
#define MAXRANGE_PEDIATRIC_ETCO2MAX		1490
#define MINRANGE_PEDIATRIC_ETCO2MIN		10

#define MAXRANGE_PEDIATRIC_FICO2MAX		1490
#define MINRANGE_PEDIATRIC_FICO2MIN		10

#define MAXRANGE_PEDIATRIC_SPO2MAX		1000//990	
#define MINRANGE_PEDIATRIC_SPO2MIN		0//10
#define MAXRANGE_PEDIATRIC_PULSERATEMAX	235
#define MINRANGE_PEDIATRIC_PULSERATEMIN	30
#define MAXRANGE_PEDIATRIC_SPO2_PIMIN	19000
#define MINRANGE_PEDIATRIC_SPO2_PIMIN	30
#define MAXRANGE_PEDIATRIC_SPO2_SIQMIN	100
#define MINRANGE_PEDIATRIC_SPO2_SIQMIN	0

#define MAXRANGE_HF_NEONATAL_MVMAX		20000
#define MINRANGE_HF_NEONATAL_MVMIN		10//rku MVLOW
//#define MAXRANGE_HF_NEONATAL_PMAX		900
//#define MAXRANGE_HF_NEONATAL_PMAX_CYLSPRING		900
#define MAXRANGE_HF_NEONATAL_PMAX	1400

#define MAXRANGE_HF_NEONATAL_MAPMAX	550
#define MINRANGE_HF_NEONATAL_MAPMIN	0

#define MINRANGE_HF_NEONATAL_PEEPMIN	-100
#define MAXRANGE_HF_NEONATAL_BPMMAX		220
#define MINRANGE_HF_NEONATAL_BPMMIN		10
#define MAXRANGE_HF_NEONATAL_LEAKMAX	50
#define MINRANGE_HF_NEONATAL_LEAKMIN	10
#define MAXRANGE_HF_NEONATAL_APNOE		20
#define MINRANGE_HF_NEONATAL_APNOE		6
#define MAXRANGE_HF_NEONATAL_DCO2MAX	10000
#define MINRANGE_HF_NEONATAL_DCO2MIN	1
#define MAXRANGE_HF_NEONATAL_ETCO2MAX_MMHG		1490
#define MINRANGE_HF_NEONATAL_ETCO2MIN_MMHG		10
#define MAXRANGE_HF_NEONATAL_ETCO2MAX_KPA		199
#define MINRANGE_HF_NEONATAL_ETCO2MIN_KPA		1
#define MAXRANGE_HF_NEONATAL_ETCO2MAX_VOL		199
#define MINRANGE_HF_NEONATAL_ETCO2MIN_VOL		1

#define MAXRANGE_HF_NEONATAL_FICO2MAX_MMHG		1490
#define MINRANGE_HF_NEONATAL_FICO2MIN_MMHG		10
#define MAXRANGE_HF_NEONATAL_FICO2MAX_KPA		199
#define MINRANGE_HF_NEONATAL_FICO2MIN_KPA		1
#define MAXRANGE_HF_NEONATAL_FICO2MAX_VOL		199
#define MINRANGE_HF_NEONATAL_FICO2MIN_VOL		1

#define MAXRANGE_HF_NEONATAL_SPO2MAX		1000//990	
#define MINRANGE_HF_NEONATAL_SPO2MIN		0//10
#define MAXRANGE_HF_NEONATAL_PULSERATEMAX	235
#define MINRANGE_HF_NEONATAL_PULSERATEMIN	30
#define MAXRANGE_HF_NEONATAL_SPO2_PIMIN		19000
#define MINRANGE_HF_NEONATAL_SPO2_PIMIN		30
#define MAXRANGE_HF_NEONATAL_SPO2_SIQMIN		100
#define MINRANGE_HF_NEONATAL_SPO2_SIQMIN		0

#define MAXRANGE_HF_PEDIATRIC_MVMAX		20000
#define MINRANGE_HF_PEDIATRIC_MVMIN		10//rku MVLOW

//#define MAXRANGE_HF_PEDIATRIC_PMAX		900
//#define MAXRANGE_HF_PEDIATRIC_PMAX_CYLSPRING		900
#define MAXRANGE_HF_PEDIATRIC_PMAX	1400

#define MAXRANGE_HF_PEDIATRIC_MAPMAX	550
#define MINRANGE_HF_PEDIATRIC_MAPMIN	0

#define MINRANGE_HF_PEDIATRIC_PEEPMIN	-100
#define MAXRANGE_HF_PEDIATRIC_BPMMAX	220
#define MINRANGE_HF_PEDIATRIC_BPMMIN	10
#define MAXRANGE_HF_PEDIATRIC_LEAKMAX	50
#define MINRANGE_HF_PEDIATRIC_LEAKMIN	10
#define MAXRANGE_HF_PEDIATRIC_APNOE		20
#define MINRANGE_HF_PEDIATRIC_APNOE		6
#define MAXRANGE_HF_PEDIATRIC_DCO2MAX		10000
#define MINRANGE_HF_PEDIATRIC_DCO2MIN		0


#define MAXRANGE_HF_PEDIATRIC_ETCO2MAX_MMHG		1490
#define MINRANGE_HF_PEDIATRIC_ETCO2MIN_MMHG		10
#define MAXRANGE_HF_PEDIATRIC_ETCO2MAX_KPA		199
#define MINRANGE_HF_PEDIATRIC_ETCO2MIN_KPA		1
#define MAXRANGE_HF_PEDIATRIC_ETCO2MAX_VOL		199
#define MINRANGE_HF_PEDIATRIC_ETCO2MIN_VOL		1

#define MAXRANGE_HF_PEDIATRIC_FICO2MAX_MMHG		1490
#define MINRANGE_HF_PEDIATRIC_FICO2MIN_MMHG		10
#define MAXRANGE_HF_PEDIATRIC_FICO2MAX_KPA		199
#define MINRANGE_HF_PEDIATRIC_FICO2MIN_KPA		1
#define MAXRANGE_HF_PEDIATRIC_FICO2MAX_VOL		199
#define MINRANGE_HF_PEDIATRIC_FICO2MIN_VOL		1

#define MAXRANGE_HF_PEDIATRIC_SPO2MAX			1000//990	
#define MINRANGE_HF_PEDIATRIC_SPO2MIN			0//10
#define MAXRANGE_HF_PEDIATRIC_PULSERATEMAX		235
#define MINRANGE_HF_PEDIATRIC_PULSERATEMIN		30
#define MAXRANGE_HF_PEDIATRIC_SPO2_PIMIN		19000
#define MINRANGE_HF_PEDIATRIC_SPO2_PIMIN		30
#define MAXRANGE_HF_PEDIATRIC_SPO2_SIQMIN		100
#define MINRANGE_HF_PEDIATRIC_SPO2_SIQMIN		0

///////locking
//neonatal
#define KEYMAX_NEONATAL_HFAmplVolG		300
#define KEYMAX_NEONATAL_PmaxVolG		250
#define KEYMAX_NEONATAL_PMan			250
#define KEYMAX_NEONATAL_CPAP			100
#define KEYMAX_NEONATAL_PInsp			250
#define KEYMAX_NEONATAL_PPSV			250
#define KEYMAX_NEONATAL_PDuo			250
#define KEYMAX_NEONATAL_PEEP			100
#define KEYMAX_NEONATAL_VGarant			300
#define KEYMAX_NEONATAL_VLimit			300

//#define KEYMAX_NEONATAL_PMitt			150
//#define KEYMAX_NEONATAL_PMitt_CYLSPRING			150
#define KEYMAX_NEONATAL_PMitt		200
//#define KEYMAX_NEONATAL_PMEAN_REC_CYLSPRING		150
#define KEYMAX_NEONATAL_PMEAN_REC	200


//#define KEYMAX_NEONATAL_HFAmpl			300
//#define KEYMAX_NEONATAL_HFAmpl_CYLSPRING			300
#define KEYMAX_NEONATAL_HFAmpl			400
#define KEYMAX_NEONATAL_HFFreq			12
#define KEYMAX_NEONATAL_FLOWTHERAPIE	5000
#define KEYMAX_NEONATAL_ITIME_REC			0
#define KEYMAX_NEONATAL_FREQ_REC			0

#define KEYMAX_NEONATAL_IFlow		20000
#define KEYMAX_NEONATAL_EFlow		20000
#define KEYMAX_PEDIATRIC_IFlow		40000//above max range
#define KEYMAX_PEDIATRIC_EFlow		40000//above max range

//pediatric
#define KEYMAX_PEDIATRIC_HFAmplVolG		400
#define KEYMAX_PEDIATRIC_PmaxVolG		250
#define KEYMAX_PEDIATRIC_PMan			250
#define KEYMAX_PEDIATRIC_CPAP			100
#define KEYMAX_PEDIATRIC_PInsp			250
#define KEYMAX_PEDIATRIC_PPSV			250
#define KEYMAX_PEDIATRIC_PDuo			250
#define KEYMAX_PEDIATRIC_PEEP			100
#define KEYMAX_PEDIATRIC_VGarant		300
#define KEYMAX_PEDIATRIC_VLimit			300

//#define KEYMAX_PEDIATRIC_PMitt			150
//#define KEYMAX_PEDIATRIC_PMitt_CYLSPRING			150
#define KEYMAX_PEDIATRIC_PMitt			200
//#define KEYMAX_PEDIATRIC_PMEAN_REC_CYLSPRING		150
#define KEYMAX_PEDIATRIC_PMEAN_REC		200

//#define KEYMAX_PEDIATRIC_HFAmpl			400
//#define KEYMAX_PEDIATRIC_HFAmpl_CYLSPRING			300
#define KEYMAX_PEDIATRIC_HFAmpl			400
#define KEYMAX_PEDIATRIC_HFFreq			12
#define KEYMAX_PEDIATRIC_FLOWTHERAPIE	5000
#define KEYMAX_PEDIATRIC_ITIME_REC		0
#define KEYMAX_PEDIATRIC_FREQ_REC		0

//neonatal
#define KEYMIN_NEONATAL_HFAmplVolG		0
#define KEYMIN_NEONATAL_PmaxVolG		0
#define KEYMIN_NEONATAL_PMan			0
#define KEYMIN_NEONATAL_CPAP			0
#define KEYMIN_NEONATAL_PInsp			0
#define KEYMIN_NEONATAL_PPSV			0
#define KEYMIN_NEONATAL_PDuo			0
#define KEYMIN_NEONATAL_PEEP			20
#define KEYMIN_NEONATAL_VGarant			0
#define KEYMIN_NEONATAL_VLimit			0
#define KEYMIN_NEONATAL_PMitt			0
#define KEYMIN_NEONATAL_HFAmpl			0
#define KEYMIN_NEONATAL_HFFreq			0
//pediatric
#define KEYMIN_PEDIATRIC_HFAmplVolG		0
#define KEYMIN_PEDIATRIC_PmaxVolG		0
#define KEYMIN_PEDIATRIC_PMan			0
#define KEYMIN_PEDIATRIC_CPAP			0
#define KEYMIN_PEDIATRIC_PInsp			0
#define KEYMIN_PEDIATRIC_PPSV			0
#define KEYMIN_PEDIATRIC_PDuo			0
#define KEYMIN_PEDIATRIC_PEEP			20
#define KEYMIN_PEDIATRIC_VGarant		0
#define KEYMIN_PEDIATRIC_VLimit			0
#define KEYMIN_PEDIATRIC_PMitt			0
#define KEYMIN_PEDIATRIC_HFAmpl			0
#define KEYMIN_PEDIATRIC_HFFreq			0


//////LIMITS
//*****************************IPPV****************************//
#define MAXRANGE_NEO_ITIME_TRIGGER			2000
#define MAXRANGE_NEO_ITIME_IPPV			2000
#define MAXRANGE_NEO_ITIME_NMODE	25000
#define MAXRANGE_NEO_ETIME_TRIGGER	30000
#define MAXRANGE_NEO_ETIME_IPPV		30000
#define MAXRANGE_NEO_ETIME_SIMV		30000
#define MAXRANGE_NEO_ETIME_NMODE	30000
#define MAXRANGE_NEO_BPM_TRIGGER	200
#define MAXRANGE_NEO_BPM_IPPV		200
#define MAXRANGE_NEO_BPM_SIMV		200
#define MAXRANGE_NEO_BPM_NMODE		80
#define MAXRANGE_NEO_RISETIME_TRIGGER	2000
#define MAXRANGE_NEO_RISETIME_IPPV		2000
#define MAXRANGE_NEO_IFLOW_TRIGGER		25000
#define MAXRANGE_NEO_IFLOW_IPPV			25000
#define MAXRANGE_NEO_HFFLOW				25000
#define MAXRANGE_NEO_EFLOW_TRIGGER		25000
#define MAXRANGE_NEO_EFLOW_IPPV			25000
#define MAXRANGE_NEO_THERAPYFLOW		19000
#define MAXRANGE_NEO_FLOWMIN			20000
#define MAXRANGE_NEO_PEEP_TRIGGER		350
#define MAXRANGE_NEO_PEEP_IPPV			350
#define MAXRANGE_NEO_CPAP				350
#define MAXRANGE_NEO_CPAP_NMODE			140
#define MAXRANGE_NEO_PINSP_TRIGGER		800
#define MAXRANGE_NEO_PINSP_IPPV			800
#define MAXRANGE_NEO_PMAXVOLG_TRIGGER	800
#define MAXRANGE_NEO_PMAXVOLG_IPPV		800
#define MAXRANGE_NEO_PPSV				800
#define MAXRANGE_NEO_PMANUAL			800
#define MAXRANGE_NEO_PMANUAL_NMODE		150
#define MAXRANGE_NEO_O2					100
#define MAXRANGE_NEO_O2FLUSH			100
#define MAXRANGE_NEO_VLIMIT_TRIGGER		2000
#define MAXRANGE_NEO_VLIMIT_IPPV		2000
#define MAXRANGE_NEO_VGARANT_TRIGGER	800
#define MAXRANGE_NEO_VGARANT_IPPV		800
#define MAXRANGE_NEO_TRIGGER_CONV		100
//#define MAXRANGE_NEO_TRIGGER_NMODE_OFF	110
#define MAXRANGE_NEO_TRIGGER_CPAP		100
//#define MAXRANGE_NEO_TRIGGER_DUOPAP_OFF		110//==off
//#define MAXRANGE_NEO_TRIGGER_NCPAP_OFF		110//==off

#define MAXRANGE_NEO_BACKUP				10
#define MAXRANGE_NEO_HFFREQ				20
#define MAXRANGE_NEO_HFVGARANT			500
#define MAXRANGE_NEO_IERATIO			RIE_1_1
#define MAXRANGE_NEO_ITIME_REC			60000
#define MAXRANGE_NEO_FREQ_REC			480
#define MAXRANGE_NEO_PMEAN_REC			600
#define MAXRANGE_NEO_HFAMPLVOLG			1500
#define MAXRANGE_NEO_HFAMPL				1500
#define MAXRANGE_NEO_HFPMEAN			600
#define MAXRANGE_ACCU_HFAMPLVOLG		600
#define MAXRANGE_ACCU_HFAMPL			600

#define MAXRANGE_NEO_FOTCONV_AMPLITUDE	100
#define MAXRANGE_NEO_FOTCONV_FREQ		20

#define MAXRANGE_NEO_FOTHFO_AMPLITUDE	100
#define MAXRANGE_NEO_FOTHFO_FREQ		20
//#define MAXRANGE_NEO_FOTHFO_PMEANSTART	600
//#define MAXRANGE_NEO_FOTHFO_PMEANEND	600
//#define MAXRANGE_NEO_FOTHFO_STEPS		21

#define MINRANGE_NEO_ITIME_TRIGGER	100
#define MINRANGE_NEO_ITIME_IPPV		100
#define MINRANGE_NEO_ITIME_NMODE	100
#define MINRANGE_NEO_ETIME_TRIGGER	200
#define MINRANGE_NEO_ETIME_IPPV		200
#define MINRANGE_NEO_ETIME_SIMV		200
#define MINRANGE_NEO_ETIME_NMODE	200
#define MINRANGE_NEO_BPM_TRIGGER	2
#define MINRANGE_NEO_BPM_IPPV		2
#define MINRANGE_NEO_BPM_SIMV		2
#define MINRANGE_NEO_BPM_NMODE		2
#define MINRANGE_NEO_RISETIME_TRIGGER		100
#define MINRANGE_NEO_RISETIME_IPPV			100
#define MINRANGE_NEO_IFLOW_TRIGGER			500
#define MINRANGE_NEO_IFLOW_IPPV				500
#define MINRANGE_NEO_HFFLOW					4000
#define MINRANGE_NEO_EFLOW_TRIGGER			1000
#define MINRANGE_NEO_EFLOW_IPPV				1000
#define MINRANGE_NEO_THERAPYFLOW			0
#define MINRANGE_NEO_FLOWMIN				2000
#define MINRANGE_NEO_PEEP_TRIGGER			0
#define MINRANGE_NEO_PEEP_IPPV				0
#define MINRANGE_NEO_PEEP_RISETIME			10
#define MINRANGE_NEO_CPAP					10
#define MINRANGE_NEO_CPAP_NMODE				10
#define MINRANGE_NEO_PINSP_TRIGGER			20
#define MINRANGE_NEO_PINSP_IPPV				20
#define MINRANGE_NEO_PMAXVOLG_TRIGGER		20
#define MINRANGE_NEO_PMAXVOLG_IPPV			20
#define MINRANGE_NEO_PPSV					20
#define MINRANGE_NEO_PMANUAL				20
#define MINRANGE_NEO_PMANUAL_NMODE			20
#define MINRANGE_NEO_O2						21
#define MINRANGE_NEO_O2FLUSH				23
#define MINRANGE_NEO_VLIMIT_TRIGGER			5
#define MINRANGE_NEO_VLIMIT_IPPV			5
#define MINRANGE_NEO_VGARANT_TRIGGER		1
#define MINRANGE_NEO_VGARANT_IPPV			1
#define MINRANGE_NEO_TRIGGER_CONV			10
//#define MINRANGE_TRIGGER_NMODE			10
#define MINRANGE_NEO_TRIGGER_DUOPAP			10
#define MINRANGE_NEO_TRIGGER_CPAP			10
#define MINRANGE_NEO_TRIGGER_NCPAP			10

#define MINRANGE_NEO_BACKUP					0
#define MINRANGE_NEO_HFAMPL					30
#define MINRANGE_NEO_HFAMPLVOLG				30
#define MINRANGE_NEO_HFFREQ					5
#define MINRANGE_NEO_HFPMEAN				50
#define MINRANGE_NEO_HFVGARANT				1 
#define MINRANGE_NEO_IERATIO				RIE_1_3
#define MINRANGE_NEO_ITIME_REC				1000
#define MINRANGE_NEO_FREQ_REC				0
#define MINRANGE_NEO_PMEAN_REC				30

#define MINRANGE_NEO_FOTCONV_AMPLITUDE		50
#define MINRANGE_NEO_FOTCONV_FREQ			5

#define MINRANGE_NEO_FOTHFO_AMPLITUDE		50
#define MINRANGE_NEO_FOTHFO_FREQ			5
//#define MINRANGE_NEO_FOTHFO_PMEANSTART		50
//#define MINRANGE_NEO_FOTHFO_PMEANEND		50
//#define MINRANGE_NEO_FOTHFO_STEPS			1

#define MAXRANGE_PED_ITIME_TRIGGER		2000
#define MAXRANGE_PED_ITIME_IPPV			2000
#define MAXRANGE_PED_ITIME_NMODE		25000
#define MAXRANGE_PED_ETIME_TRIGGER		30000
#define MAXRANGE_PED_ETIME_IPPV			30000
#define MAXRANGE_PED_ETIME_SIMV			30000
#define MAXRANGE_PED_ETIME_NMODE		30000
#define MAXRANGE_PED_BPM_TRIGGER		150
#define MAXRANGE_PED_BPM_IPPV			150
#define MAXRANGE_PED_BPM_SIMV			150
#define MAXRANGE_PED_BPM_NMODE			80
#define MAXRANGE_PED_RISETIME_IPPV		2000
#define MAXRANGE_PED_RISETIME_TRIGGER	2000
#define MAXRANGE_PED_IFLOW_TRIGGER		32000
#define MAXRANGE_PED_IFLOW_IPPV			32000
#define MAXRANGE_PED_HFFLOW				25000
#define MAXRANGE_PED_EFLOW_TRIGGER		25000
#define MAXRANGE_PED_EFLOW_IPPV			25000
#define MAXRANGE_PED_THERAPYFLOW		19000
#define MAXRANGE_PED_FLOWMIN			20000
#define MAXRANGE_PED_PEEP_TRIGGER		350
#define MAXRANGE_PED_PEEP_IPPV			350
#define MAXRANGE_PED_CPAP				350
#define MAXRANGE_PED_CPAP_NMODE			140
#define MAXRANGE_PED_PINSP_TRIGGER		800
#define MAXRANGE_PED_PINSP_IPPV			800
#define MAXRANGE_PED_PMAXVOLG_TRIGGER	800
#define MAXRANGE_PED_PMAXVOLG_IPPV		800
#define MAXRANGE_PED_PPSV				800
#define MAXRANGE_PED_PMANUAL			800
#define MAXRANGE_PED_PMANUAL_NMODE		150
#define MAXRANGE_PED_O2					100
#define MAXRANGE_PED_O2FLUSH			100
#define MAXRANGE_PED_VLIMIT_TRIGGER		5000
#define MAXRANGE_PED_VLIMIT_IPPV		5000
#define MAXRANGE_PED_VGARANT_TRIGGER	3500
#define MAXRANGE_PED_VGARANT_IPPV		3500
#define MAXRANGE_PED_TRIGGER_CONV		100
//#define MAXRANGE_TRIGGER_NMODE_OFF		110// 110 == 0ff
#define MAXRANGE_PED_TRIGGER_CPAP			100
//#define MAXRANGE_PED_TRIGGER_DUOPAP_OFF		110// == 0ff
//#define MAXRANGE_PED_TRIGGER_NCPAP_OFF		110// == 0ff

#define MAXRANGE_TRIGGER_OFF		110// == 0ff
#define TRIGGER_SENSITIVITY_AUTO	10

#define MAXRANGE_PED_BACKUP				10
#define MAXRANGE_PED_HFFREQ				20
#define MAXRANGE_PED_ITIME_REC			60000
#define MAXRANGE_PED_FREQ_REC			480
#define MAXRANGE_PED_PMEAN_REC			600
#define MAXRANGE_PED_HFVGARANT			1500
#define MAXRANGE_PED_IERATIO			RIE_1_1
#define MAXRANGE_PED_HFAMPL				1500
#define MAXRANGE_PED_HFAMPLVOLG			1500
#define MAXRANGE_PED_HFPMEAN			600
//#define MAXRANGE_PED_PMEAN_FOT			600

#define MAXRANGE_PED_FOTCONV_AMPLITUDE	100
#define MAXRANGE_PED_FOTCONV_FREQ		20

#define MAXRANGE_PED_FOTHFO_AMPLITUDE	100
#define MAXRANGE_PED_FOTHFO_FREQ		20
//#define MAXRANGE_PED_FOTHFO_PMEANSTART	600
//#define MAXRANGE_PED_FOTHFO_PMEANEND	600
//#define MAXRANGE_PED_FOTHFO_STEPS		21

#define MINRANGE_PED_ITIME_TRIGGER		200
#define MINRANGE_PED_ITIME_IPPV			200
#define MINRANGE_PED_ITIME_NMODE		100
#define MINRANGE_PED_ETIME_TRIGGER		200
#define MINRANGE_PED_ETIME_IPPV			200
#define MINRANGE_PED_ETIME_SIMV			200
#define MINRANGE_PED_ETIME_NMODE		200
#define MINRANGE_PED_BPM_TRIGGER		2
#define MINRANGE_PED_BPM_IPPV			2
#define MINRANGE_PED_BPM_SIMV			2
#define MINRANGE_PED_BPM_NMODE			2
#define MINRANGE_PED_RISETIME_TRIGGER	200
#define MINRANGE_PED_RISETIME_IPPV		200
#define MINRANGE_PED_IFLOW_TRIGGER		1000
#define MINRANGE_PED_IFLOW_IPPV			1000
#define MINRANGE_PED_HFFLOW				4000
#define MINRANGE_PED_EFLOW_TRIGGER		2000
#define MINRANGE_PED_EFLOW_IPPV			2000
#define MINRANGE_PED_THERAPYFLOW		0
#define MINRANGE_PED_FLOWMIN			2000
#define MINRANGE_PED_PEEP_TRIGGER		0
#define MINRANGE_PED_PEEP_IPPV			0
#define MINRANGE_PED_PEEP_RISETIME		10
#define MINRANGE_PED_CPAP				10
#define MINRANGE_PED_CPAP_NMODE			10
#define MINRANGE_PED_PINSP_TRIGGER		20
#define MINRANGE_PED_PINSP_IPPV			20
#define MINRANGE_PED_PMAXVOLG_TRIGGER	20
#define MINRANGE_PED_PMAXVOLG_IPPV		20
#define MINRANGE_PED_PPSV				20
#define MINRANGE_PED_PMANUAL			20
#define MINRANGE_PED_PMANUAL_NMODE		20
#define MINRANGE_PED_O2					21
#define MINRANGE_PED_O2FLUSH			23
#define MINRANGE_PED_VLIMIT_TRIGGER		20
#define MINRANGE_PED_VLIMIT_IPPV		20
#define MINRANGE_PED_VGARANT_TRIGGER	20
#define MINRANGE_PED_VGARANT_IPPV		20
#define MINRANGE_PED_TRIGGER_CONV		10
//#define MINRANGE_PED_TRIGGER_NMODE	10
#define MINRANGE_PED_TRIGGER_CPAP		10
#define MINRANGE_PED_TRIGGER_DUOPAP		10
#define MINRANGE_PED_TRIGGER_NCPAP		10


#define MINRANGE_PED_BACKUP				0
#define MINRANGE_PED_HFAMPL				30
#define MINRANGE_PED_HFAMPLVOLG			30
#define MINRANGE_PED_HFFREQ				5
#define MINRANGE_PED_HFPMEAN			50
#define MINRANGE_PED_HFVGARANT			20
#define MINRANGE_PED_IERATIO			RIE_1_3
#define MINRANGE_PED_ITIME_REC			1000
#define MINRANGE_PED_FREQ_REC			0
#define MINRANGE_PED_PMEAN_REC			30
#define MINRANGE_PED_PMEAN_FOT			30

#define MINRANGE_PED_FOTCONV_AMPLITUDE	50
#define MINRANGE_PED_FOTCONV_FREQ		5

#define MINRANGE_PED_FOTHFO_AMPLITUDE	50
#define MINRANGE_PED_FOTHFO_FREQ		5
//#define MINRANGE_PED_FOTHFO_PMEANSTART	50
//#define MINRANGE_PED_FOTHFO_PMEANEND	50
//#define MINRANGE_PED_FOTHFO_STEPS		1

////maximum/minimum of scale type dependend
//#define G_UPPER_MAXSCALE_CLFIO2				250	
//#define G_LOWER_MAXSCALE_CLFIO2				2
//
//#define G_UPPER_MAXSCALE_EMG				250	
//#define G_LOWER_MAXSCALE_EMG				2

#define G_UPPER_MAXSCALE_SPO2				120	
#define G_LOWER_MAXSCALE_SPO2				10

#define G_UPPER_MAXSCALE_SPO2PR				250	
#define G_LOWER_MAXSCALE_SPO2PR				10

#define G_UPPER_MAXSCALE_CO2				160	
#define G_LOWER_MAXSCALE_CO2				10

#define G_UPPER_MAXSCALE_NMODEPRESSURE		20	
#define G_UPPER_MAXSCALE_PRESSURE			100	
#define G_LOWER_MAXSCALE_PRESSURE			10	

#define G_UPPER_MAXSCALE_PRESSUREHF			200	
#define G_LOWER_MAXSCALE_PRESSUREHF			0
#define G_UPPER_MINSCALE_PRESSUREHF			0	
#define G_LOWER_MINSCALE_PRESSUREHF			-200
#define G_LOWER_MINSCALE_PRESSURE			-100

//#define G_UPPER_MAXSCALE_PMEAN_FOT			600
#define G_LOWER_MAXSCALE_PRESSURE_FOT			10
#define G_UPPER_MAXSCALE_XRS_FOT			100//rku, check FOTGRAPH
//#define G_UPPER_MINSCALE_XRS_FOT			-10
#define G_LOWER_MINSCALE_XRS_FOT			-500	

#define G_UPPER_MAXSCALE_FLOW				80	
#define G_LOWER_MAXSCALE_FLOW				2	

#define G_UPPER_MAXSCALE_VOLUME_NEO			60	
#define G_UPPER_MAXSCALE_VOLUME_PED			300

#define G_UPPER_MAXSCALE_VOLUME_HF			80
#define G_LOWER_MAXSCALE_VOLUME				2 //newVG
#define G_LOWER_MAXSCALE_VOLUME_HF			2
#define G_UPPER_MAXSCALE_FIO2				1200//newtrend
#define G_LOWER_MAXSCALE_FIO2				200//newtrend
#define G_UPPER_MAXSCALE_VTE				600	
#define G_LOWER_MAXSCALE_VTE				10
#define G_UPPER_MAXSCALE_COMPL				1200	
#define G_LOWER_MAXSCALE_COMPL				100
#define G_UPPER_MAXSCALE_DCO2				5000	
#define G_LOWER_MAXSCALE_DCO2				10
#define G_UPPER_MAXSCALE_MV					10000	
#define G_LOWER_MAXSCALE_MV					100//newtrend
#define G_UPPER_MAXSCALE_HFAMP				100	
#define G_LOWER_MAXSCALE_HFAMP				10
#define G_UPPER_MAXSCALE_RSBI				2500	
#define G_LOWER_MAXSCALE_RSBI				50//newtrend
#define G_UPPER_MAXSCALE_SHAREMVMAND		120	
#define G_LOWER_MAXSCALE_SHAREMVMAND		10
#define G_UPPER_MAXSCALE_RESISTANCE			10000	 
#define G_LOWER_MAXSCALE_RESISTANCE			100//newtrend
#define G_UPPER_MAXSCALE_LEAK				120	
#define G_LOWER_MAXSCALE_LEAK				10
#define G_UPPER_MAXSCALE_SPO2PI				200	
#define G_LOWER_MAXSCALE_SPO2PI				50
#define G_UPPER_MAXSCALE_FREQUENCY			300	
#define G_LOWER_MAXSCALE_FREQUENCY			20


//factory defaults
//#define FACTORY_SPO2_SIQLIMIT		30

#define FACTORY_CPAP_BACKUP				0

#define FACTORY_NMODE_BPM				30
#define FACTORY_NMODE_ITIME			1000
#define FACTORY_NMODE_ETIME			1000

//#define FACTORY_NMODE_TRIGGER			110

#define FACTORY_SIMVPSV_TRIGGER			50
#define FACTORY_SIMVPSV_ETIME			3400
#define FACTORY_SIMVPSV_BPM				15
#define FACTORY_SIMVPSV_ITIME			600

#define FACTORY_PSV_TRIGGER				50
#define FACTORY_PSV_BPM					40
#define FACTORY_PSV_ITIME				400
#define FACTORY_PSV_ETIME				1100

#define FACTORY_IPPV_BPM				60
#define FACTORY_IPPV_ITIME				500
#define FACTORY_IPPV_ETIME				500

#define FACTORY_SIPPV_TRIGGER			50
#define FACTORY_SIPPV_BPM				40
#define FACTORY_SIPPV_ITIME				500
#define FACTORY_SIPPV_ETIME				1000



#define FACTORY_SIMV_TRIGGER			50
#define FACTORY_SIMV_BPM				15
#define FACTORY_SIMV_ITIME				600
#define FACTORY_SIMV_ETIME				3400

#define FACTORY_CPAP_TRIGGER			50
#define FACTORY_DUOPAP_TRIGGER			50
#define FACTORY_NCPAP_TRIGGER			50

#define FACTORY_HFO_HFAMPL				200
#define FACTORY_HFO_HFFREQ				10
#define FACTORY_HFO_VGARANT				8
#define FACTORY_HFO_VGARANTSTATE		0
#define FACTORY_HFO_IERATIO				0
#define FACTORY_HFO_PMEAN				100

#define FACTORY_HFO_ITIMEREC			5000
#define FACTORY_HFO_FREQREC				0
#define FACTORY_HFO_PMEANREC			200

//FOT
#define FACTORY_FOT_CONV_FREQ			10
#define FACTORY_FOT_CONV_AMPL			50
#define FACTORY_FOT_CONV_STEPS			11
#define FACTORY_FOT_CONV_PEEP_START		100
#define FACTORY_FOT_CONV_PEEP_END		200

#define FACTORY_FOT_HFO_FREQ			8
#define FACTORY_FOT_HFO_STEPS			11
#define FACTORY_FOT_HFO_AMPL			50
#define FACTORY_FOT_HFO_PMEAN_START		100
#define FACTORY_FOT_HFO_PMEAN_END		200

//#define FACTORY_PPSV					20
#define FACTORY_FLOWMIN					4000
#define FACTORY_PMAN					150
#define FACTORY_CPAP					50
#define FACTORY_PMAXVOLG				150
#define FACTORY_PINSP					150
#define FACTORY_PEEP					50
//#define FACTORY_PLATEAU					0
#define FACTORY_RISETIME				500
#define FACTORY_IFLOW					8000
#define FACTORY_HFFLOW					8000
#define FACTORY_EFLOW					4000
#define FACTORY_VLIMIT					10
#define FACTORY_VLIMITSTATE				0
#define FACTORY_VGARANT					12
#define FACTORY_VGARANTSTATE			0
#define FACTORY_O2FLUSH					23
#define FACTORY_O2						21
#define FACTORY_THERAPYFLOW				4000

#define FACTORY_ALIMIT_VAL_ETCO2MAX_VOL		800
#define FACTORY_ALIMIT_VAL_ETCO2MAX_KPA		800
#define FACTORY_ALIMIT_VAL_ETCO2MAX_MMHG	600
#define FACTORY_ALIMIT_STATE_ETCO2MAX	AL_ON
#define FACTORY_ALIMIT_VAL_ETCO2MIN_VOL		10
#define FACTORY_ALIMIT_VAL_ETCO2MIN_KPA		10
#define FACTORY_ALIMIT_VAL_ETCO2MIN_MMHG	80
#define FACTORY_ALIMIT_STATE_ETCO2MIN	AL_ON

#define FACTORY_ALIMIT_VAL_FICO2MAX_VOL		800
#define FACTORY_ALIMIT_VAL_FICO2MAX_KPA		800
#define FACTORY_ALIMIT_VAL_FICO2MAX_MMHG	600
#define FACTORY_ALIMIT_STATE_FICO2MAX	AL_ON
#define FACTORY_ALIMIT_VAL_FICO2MIN_VOL		10
#define FACTORY_ALIMIT_VAL_FICO2MIN_KPA		10
#define FACTORY_ALIMIT_VAL_FICO2MIN_MMHG	80
#define FACTORY_ALIMIT_STATE_FICO2MIN	AL_ON

#define FACTORY_ALIMIT_VAL_SPO2MAX			990
#define FACTORY_ALIMIT_STATE_SPO2MAX		AL_ON
#define FACTORY_ALIMIT_VAL_SPO2MIN			880
#define FACTORY_ALIMIT_STATE_SPO2MIN		AL_ON
#define FACTORY_ALIMIT_VAL_PULSERATEMAX		180
#define FACTORY_ALIMIT_STATE_PULSERATEMAX	AL_ON
#define FACTORY_ALIMIT_VAL_PULSERATEMIN		100
#define FACTORY_ALIMIT_STATE_PULSERATEMIN	AL_ON
#define FACTORY_ALIMIT_VAL_SPO2_PIMIN		0
#define FACTORY_ALIMIT_STATE_SPO2_PIMIN	AL_ON

#define FACTORY_ALIMIT_VAL_SPO2_SIQMIN		0
#define FACTORY_ALIMIT_STATE_SPO2_SIQMIN	AL_OFF

#define FACTORY_ALIMIT_VAL_MVMAX		1500
#define FACTORY_ALIMIT_STATE_MVMAX		AL_ON
#define FACTORY_ALIMIT_VAL_MVMIN		100
#define FACTORY_ALIMIT_STATE_MVMIN		AL_ON
#define FACTORY_ALIMIT_VAL_PIPMAX		180
#define FACTORY_ALIMIT_STATE_PIPMAX		AL_AUTO
#define FACTORY_ALIMIT_VAL_PIPMIN		170
#define FACTORY_ALIMIT_STATE_PIPMIN		AL_AUTO
#define FACTORY_ALIMIT_VAL_PEEP			20
#define FACTORY_ALIMIT_STATE_PEEP		AL_AUTO
#define FACTORY_ALIMIT_VAL_BPMMAX		90
#define FACTORY_ALIMIT_STATE_BPMMAX		AL_OFF
#define FACTORY_ALIMIT_VAL_LEAKMAX		0
#define FACTORY_ALIMIT_STATE_LEAKMAX	AL_OFF
#define FACTORY_ALIMIT_VAL_APNOE		10
#define FACTORY_ALIMIT_STATE_APNOE		AL_ON
#define FACTORY_ALIMIT_VAL_DCO2MAX		1500
#define FACTORY_ALIMIT_STATE_DCO2MAX	AL_ON
#define FACTORY_ALIMIT_VAL_DCO2MIN		100
#define FACTORY_ALIMIT_STATE_DCO2MIN	AL_ON

#define FACTORY_ALIMIT_VAL_MAPMAX		150
#define FACTORY_ALIMIT_STATE_MAPMAX	AL_ON
#define FACTORY_ALIMIT_VAL_MAPMIN		50
#define FACTORY_ALIMIT_STATE_MAPMIN	AL_ON


#define FACTORY_NUMBLOCK	0

//#define FACTORY_ALIMIT_VAL_MVMAX			1500
//#define FACTORY_ALIMIT_STATE_MVMAX			AL_ON
#define FACTORY_ALIMIT_VAL_MVMIN_HF			150
//#define FACTORY_ALIMIT_STATE_MVMIN			AL_ON
//#define FACTORY_ALIMIT_VAL_PMAX				180
//#define FACTORY_ALIMIT_STATE_PMAX			AL_AUTO
//#define FACTORY_ALIMIT_VAL_PEEP				20
//#define FACTORY_ALIMIT_STATE_PEEP			AL_AUTO
//#define FACTORY_ALIMIT_VAL_BPMMAX			90
//#define FACTORY_ALIMIT_STATE_BPMMAX			AL_OFF
//#define FACTORY_ALIMIT_VAL_LEAKMAX			0
//#define FACTORY_ALIMIT_STATE_LEAKMAX		AL_OFF
#define FACTORY_ALIMIT_VAL_APNOE_HF			10
#define FACTORY_ALIMIT_STATE_APNOE_HF		AL_ON





//FRAM-Settings for configuration FabianHFO, 
//FRAM Address DEVICE_ADDRESS_CONFIG 0x50<<1  // Bit7..4=devicetype=1010b, Bit3..2=address select bits, Bit1 = page select = MSB, Bit0 = read/write Bit -> 1=read, 0=write
// 
//Address of config FRAM FM24V10 1Mbit, address 17bit -> including a page select bit, beginning Address = 0x0000,  last Address = 0xffff,
//also
//Address of config FRAM64k, 16bit -> but only 13bits used, the upper 3bits are don't care, MSB, LSB, last Address = 0x1fff,


//first Config-Address at 0x0000, last Addresss 0x16FF, -> 5888 Byte available for config, rest is reserved for trends!!!!!!!!
//WORKSTATES
//#define LANGUAGEID_8					0x0000
#define VENTRANGE_8						0x0001
#define CURVENTMODE_8					0x0002
#define PREVVENTMODE_8					0x0003
#define ALARMVOLUME_8					0x0004
#define MANBREATHTIME_8					0x0005
#define O2FLUSHTIME_8					0x0006
#define REFFLOWSENSOR_8					0x0007
#define LASTTRIGGERMODE_8				0x0008
#define TRIGGERTYPECONV_8				0x0009
#define PMINALARMDELAY_8				0x000A
#define LASTNMODE_8						0x000B
#define IERELATIONMODE_8				0x000C
#define TUBESET_8						0x000D
#define USETVEBTB_8						0x000E
#define PATIENTALARMDELAY_8				0x000F
#define LASTVENTILATIONSUBVIEW_8		0x0010
#define ABORTCRITERIONPSV_8				0x0011
#define AUTOOXYCAL_8					0x0012
#define AUTOSCREENLOCKTIME_8			0x0013
#define AUTOSCREENLOCKSTATE_8			0x0014
#define SERVICEPSWRDDISABLED_8			0x0015
#define HFOMANBREATH_8					0x0016
#define NURSECALLACTIVE_8				0x0017
#define FLOWSENSORSTATE_8				0x0018
#define CO2UNIT_8						0x0019
#define BTPS_8							0x001A
#define CO2BAROPRESSURE_16				0x001B
#define CO2TIMEPUMPAUTOON				0x001D
#define PRESSUREUNIT_8					0x001E
#define VOLUMECONTROL_8					0x001F
#define TRIGGERTYPENCPAP_8				0x0020
#define PRESSURERISECTRL_8				0x0021
#define NEBULIZERTIME_8					0x0022
#define EFLOWEQUIFLOW_8					0x0023
#define SPO2FASTSAT_8					0x0024
#define FACTORYSETTINGS_8				0x0025
#define AUTOALARMLIMIT_8				0x0026
#define PPSV_AS_PEEPDELTA_8				0x0027
#define ALIMITLASTNUMERICSTATE_8		0x0028
#define SPO2SENSITIVITY_8				0x0029
#define SPO2ALARMDELAY_8				0x002A
#define SPO2AVERAGINGTIME_8				0x002B
#define FRESHGASEXT_8					0x002C
#define EFLOWSETTINGS_8					0x002D
#define LEAKCOMPENSATIONOFF_8			0x002E

#define NUMBLOCK_IPPV_8					0x0030
#define NUMBLOCK_SIPPV_8				0x0031
#define NUMBLOCK_SIMV_8					0x0032
#define NUMBLOCK_SIMVPSV_8				0x0033
#define NUMBLOCK_PSV_8					0x0034
#define NUMBLOCK_CPAP_8					0x0035
#define NUMBLOCK_HFO_8					0x0036
#define NUMBLOCK_NCPAP_8				0x0037
#define NUMBLOCK_DUOPAP_8				0x0038
#define NUMBLOCK_THERAPY_8				0x0039

#define PRICOSPO2LOW_8				0x0040
#define PRICOSPO2HIGH_8				0x0041
#define PRICOFIO2LOW_8				0x0042
#define PRICOFIO2HIGH_8				0x0043

#define SERVICE_DAY_8					0x0045
#define SERVICE_MONTH_8					0x0046
#define SERVICE_YEAR_16					0x0047

#define ALTITUDE_16					0x0049
#define FLOW_CORFACTOR_NEO_16		0x004B
#define FLOW_CORFACTOR_PED_16		0x004D

#define NUMBLOCK_FLOWOFFCONV_8			0x004F
#define NUMBLOCK_FLOWOFFHFO_8			0x0050

#define USENEOPED_8						0x0051
#define NUMBLOCK_FLOWOFFCPAP_8			0x0052

#define TRIGGERTYPECPAP_8				0x0053
#define TRIGGERTYPEDUOPAP_8				0x0054

//PARA DATA
#define PARA_ITIME_IPPV_16				0x0060
#define PARA_ITIME_NMODE_16				0x0062
#define PARA_ETIME_IPPV_16				0x0064
#define PARA_ETIME_NMODE_16				0x0066
#define PARA_BPM_IPPV_16				0x0068
#define PARA_BPM_NMODE_16				0x006A
#define PARA_IFLOW_IPPV_16				0x006C
#define PARA_EFLOW_IPPV_16				0x006E
#define PARA_FLOWMIN_16					0x0070
#define PARA_PEEP_IPPV_16				0x0072
#define PARA_CPAP_16					0x0074
#define PARA_CPAP_NMODE_16				0x0076
#define PARA_PINSP_IPPV_16				0x0078
#define PARA_PMAXVOLG_IPPV_16			0x007A
#define PARA_PPSV_16					0x007C
#define PARA_PMAN_HFO_16				0x007E
#define PARA_PMAN_NMODE_16				0x0080
#define PARA_O2_16						0x0082
#define PARA_O2FLUSH_16					0x0084
#define PARA_O2DIFF_16					0x0086
#define PARA_VLIMIT_IPPV_16				0x0088
#define PARA_VLIMITSTATE_IPPV_8			0x008A
#define PARA_VGARANT_IPPV_16			0x008C
#define PARA_VGARANTSTATE_IPPV_8		0x008E
//#define PARA_TRIGGER_CONV_16			0x0090
#define PARA_BACKUP_16					0x0092
#define PARA_HFO_HFAMPL_16				0x0094
#define PARA_HFO_HFAMPL_VOLG_16			0x0096
#define PARA_HFO_HFFREQ_16				0x0098
#define PARA_HFO_PMEAN_16				0x009A
#define PARA_HFO_IERATIO_8				0x009C
#define PARA_HFO_VGARANT_16				0x009D
#define PARA_HFO_VGARANTSTATE_8			0x0100
#define PARA_HFO_ITIMEREC16				0x0102
#define PARA_HFO_FREQREC16				0x0104
#define PARA_HFO_PMEANREC16				0x0106
#define PARA_HFFLOW_16					0x0108
#define PARA_PPSVDIFF_16				0x010A

#define PARA_RISETIME_IPPV_16			0x0110
#define PARA_PMEANDIFF_16				0x0112
#define PARA_THERAPYFLOW_16				0x0114
#define PARA_PMAN_CPAP_16				0x0116

#define PARA_FOT_CONV_FREQ_8			0x0118
#define PARA_FOT_CONV_AMPLITUDE_16		0x0119
#define PARA_FOT_HFO_AMPLITUDE_16		0x011B
#define PARA_FOT_HFO_FREQ_8				0x011D
#define PARA_FOT_HFO_PMEANSTART_16		0x011E
#define PARA_FOT_HFO_PMEANEND_16		0x0120
#define PARA_FOT_HFO_STEPS_8			0x0122
#define PARA_FOT_CONV_PEEPSTART_16		0x0124
#define PARA_FOT_CONV_PEEPEND_16		0x0126
#define PARA_FOT_CONV_STEPS_8			0x0128

#define PARA_TRIGGER_DUOPAP_16			0x0129
#define PARA_TRIGGER_NCPAP_16			0x012B
#define PARA_TRIGGER_CPAP_16			0x012D
#define PARA_TRIGGER_CONVENT_16			0x012F

//ALARM DATA
#define ALIMIT_VAL_SPO2MAX_16			0x0182
#define ALIMIT_VAL_SPO2MIN_16			0x0184
#define ALIMIT_VAL_PULSERATEMAX_16		0x0186
#define ALIMIT_VAL_PULSERATEMIN_16		0x0188
#define ALIMIT_VAL_SPO2_PIMIN_16		0x018A
#define ALIMIT_VAL_SPO2_SIQMIN_16		0x018C
#define ALIMIT_VAL_PIPMIN_16			0x018E
#define ALIMIT_VAL_MVMAX_16				0x0190
#define ALIMIT_VAL_MVMIN_16				0x0192
#define ALIMIT_VAL_PIPMAX_16			0x0194
#define ALIMIT_VAL_PEEP_16				0x0196
#define ALIMIT_VAL_BPMMAX_16			0x0198
#define ALIMIT_VAL_LEAKMAX_16			0x019A
#define ALIMIT_VAL_APNOE_16				0x019C

#define ALIMIT_STATE_MVMAX_8			0x01A0
#define ALIMIT_STATE_MVMIN_8			0x01A1
#define ALIMIT_STATE_PIPMAX_8			0x01A2
#define ALIMIT_STATE_PEEP_8				0x01A3
#define ALIMIT_STATE_BPMMAX_8			0x01A4
#define ALIMIT_STATE_LEAKMAX_8			0x01A5
#define ALIMIT_STATE_APNOE_8			0x01A6
#define ALIMIT_STATE_PIPMIN_8			0x01A7
//#define ALIMIT_STATE_ETCO2MIN_8			0x01A8
#define ALIMIT_STATE_SPO2MAX_8			0x01A9
#define ALIMIT_STATE_SPO2MIN_8			0x01AA
#define ALIMIT_STATE_PULSERATEMAX_8		0x01AB
#define ALIMIT_STATE_PULSERATEMIN_8		0x01AC
#define ALIMIT_STATE_SPO2_PIMIN_8		0x01AD
#define ALIMIT_STATE_SPO2_SIQMIN_8		0x01AE
//#define ALIMIT_STATE_FICO2MIN_8			0x01AF

//TREND STATES
#define TREND_SPAN_16					0x01B0
#define TRENDSCALE_PINSP_16				0x01B2
#define TRENDSCALE_PMEAN_16				0x01B4
#define TRENDSCALE_FIO2_16				0x01B6
#define TRENDSCALE_VTE_16				0x01B8
#define TRENDSCALE_COMPLIANCE_16		0x01BA
#define TRENDSCALE_DCO2_16				0x01BC
#define TRENDSCALE_MV_16				0x01BE
#define TRENDSCALE_HFAMP_16				0x01C0

#define FILLEDTREND_8					0x01CA
#define TREND_TYPE1_8					0x01CB
#define TREND_TYPE2_8					0x01CC
#define TREND_TYPE3_8					0x01CD
#define TRENDAUTOSCALE_8				0x01CE

//GRAPH STATES
#define FILLEDGRAPH_8					0x01D0
#define GRAPHAUTOSCALE_8				0x01D2
#define GRAPHLASTVIEWSUBSTATE_8			0x01D4
#define GRAPHSPEEDNORM_8				0x01D6
#define GRAPHSPEEDHFO_8					0x01D7
#define CURLINEDIAGRAMM_8				0x01D8
#define GRAPHSPEEDCLFIO2_8				0x01D9

#define MAXSCALE_FLOW_GRAPH_16			0x01DA
#define MAXSCALE_PRESSURE_GRAPH_16		0x01DC
#define MAXSCALE_VOLUME_GRAPH_16		0x01DE

#define MAXSCALE_FLOW_HFGRAPH_16		0x01E0
#define MAXSCALE_VOLUME_HFGRAPH_16		0x01E2
#define MAXSCALE_PRESSURE_HFGRAPH_16	0x01E4
#define MINSCALE_PRESSURE_HFGRAPH_16	0x01E6

#define MAXSCALE_PRESSURE_HFPVLOOP_16	0x01E8
#define MINSCALE_PRESSURE_HFPVLOOP_16	0x01EA
#define MAXSCALE_VOLUME_HFPVLOOP_16		0x01EC
#define MAXSCALE_FLOW_HFVFLOOP_16		0x01EE
#define MAXSCALE_VOLUME_HFVFLOOP_16		0x01F0

#define MAXSCALE_PRESSURE_PVLOOP_16		0x01F2
#define MAXSCALE_VOLUME_PVLOOP_16		0x01F4
#define MAXSCALE_VOLUME_VFLOOP_16		0x01F6
#define MAXSCALE_FLOW_VFLOOP_16			0x01F8


//ALARM DATA HF
#define ALIMIT_VAL_PULSERATEMAX_HF_16	0x01FA
#define ALIMIT_VAL_PULSERATEMIN_HF_16	0x01FC
#define ALIMIT_VAL_SPO2_PIMIN_HF_16		0x01FE
#define ALIMIT_VAL_MVMAX_HF_16			0x0200
#define ALIMIT_VAL_MVMIN_HF_16			0x0202
#define ALIMIT_VAL_PMAX_HF_16			0x0204
#define ALIMIT_VAL_PEEP_HF_16			0x0206
#define ALIMIT_VAL_BPMMAX_HF_16			0x0208
#define ALIMIT_VAL_LEAKMAX_HF_16		0x020A
#define ALIMIT_VAL_APNOE_HF_16			0x020C
#define ALIMIT_STATE_DCO2MAX_HF_8		0x020E
#define ALIMIT_STATE_DCO2MIN_HF_8		0x020F
#define ALIMIT_STATE_MVMAX_HF_8			0x0210
#define ALIMIT_STATE_MVMIN_HF_8			0x0211
#define ALIMIT_STATE_PMAX_HF_8			0x0212
#define ALIMIT_STATE_PEEP_HF_8			0x0213
#define ALIMIT_STATE_BPMMAX_HF_8		0x0214
#define ALIMIT_STATE_LEAKMAX_HF_8		0x0215
#define ALIMIT_STATE_APNOE_HF_8			0x0216
#define ALIMIT_VAL_DCO2MAX_HF_16		0x0217
#define ALIMIT_VAL_DCO2MIN_HF_16		0x0219
#define ALIMIT_STATE_SPO2MAX_HF_8		0x0221
#define ALIMIT_STATE_SPO2MIN_HF_8		0x0222
#define ALIMIT_STATE_PULSERATEMAX_HF_8	0x0223

//ALARM DATA CPAP
#define ALIMIT_VAL_PMAX_CPAP_16			0x0224
#define ALIMIT_VAL_PEEP_CPAP_16			0x0226

#define ALIMIT_VAL_SPO2MAX_HF_16		0x0228
#define ALIMIT_VAL_SPO2MIN_HF_16		0x022A
#define ALIMIT_STATE_PULSERATEMIN_HF_8	0x022C
#define ALIMIT_STATE_SPO2_PIMIN_HF_8	0x022D
#define ALIMIT_STATE_SPO2_SIQMIN_HF_8	0x022E

#define ALIMIT_STATE_PMAX_CPAP_8		0x0232
#define ALIMIT_STATE_PEEP_CPAP_8		0x0233

#define ALIMIT_VAL_SPO2_SIQMIN_HF_16	0x0234

#define ALIMIT_STATE_MAPMAX_HF_8		0x0236
#define ALIMIT_STATE_MAPMIN_HF_8		0x0237
#define ALIMIT_VAL_MAPMAX_HF_16			0x0238
#define ALIMIT_VAL_MAPMIN_HF_16			0x023A

//#define ALIMIT_VAL_PMAX_NMODE_16		0x0234
//#define ALIMIT_VAL_PEEP_NMODE_16		0x0236
//#define ALIMIT_STATE_PMAX_NMODE_8		0x0238
//#define ALIMIT_STATE_PEEP_NMODE_8		0x0239

//#define ALIMIT_VAL_FICO2MAX_16			0x0234
//#define ALIMIT_VAL_FICO2MIN_16			0x0236
//
//#define ALIMIT_VAL_FICO2MAX_HF_16		0x0238
//#define ALIMIT_VAL_FICO2MIN_HF_16		0x023A
//#define ALIMIT_STATE_FICO2MAX_HF_8		0x023C
//#define ALIMIT_STATE_FICO2MIN_HF_8		0x023D


//LAST WRITTEN TREND FILE NUMBERS
#define TRENDFILE_PINSP_8				0x0240
#define TRENDFILE_PMEAN_8				0x0241
#define TRENDFILE_FIO2_8				0x0242
#define TRENDFILE_VTE_8					0x0243
#define TRENDFILE_COMPLIANCE_8			0x0244
#define TRENDFILE_CO2HFO_8				0x0245
#define TRENDFILE_MV_8					0x0246
#define TRENDFILE_HFAMP_8				0x0247
#define TRENDFILE_RSBI_8				0x0248
#define TRENDFILE_SHAREMVMAND_8			0x0249
#define TRENDFILE_RESISTANCE_8			0x024A
#define TRENDFILE_LEAK_8				0x024B
#define TRENDFILE_SPO2_8				0x024C
#define TRENDFILE_SPO2PI_8				0x024D
#define TRENDFILE_ETCO2_8				0x024E
#define TRENDFILE_SPO2PR_8				0x024F
#define TRENDFILE_FREQUENCY_8			0x0250

#define MAXSCALE_CO2_GRAPH_16			0x0260
#define MAXSCALE_CO2_HFGRAPH_16			0x0262

#define MAXSCALE_SPO2_GRAPH_16			0x0264
#define MAXSCALE_SPO2_HFGRAPH_16		0x0266

#define MAXSCALE_FOT_PRESSURE_16		0x0268
#define MINSCALE_FOT_XRS_16				0x026A

#define ALIMIT_VAL_PMAX_DUOPAP_16		0x0270
#define ALIMIT_VAL_PEEP_DUOPAP_16		0x0272
#define ALIMIT_STATE_PMAX_DUOPAP_8		0x0274
#define ALIMIT_STATE_PEEP_DUOPAP_8		0x0275

#define ALIMIT_VAL_PMAX_NCPAP_16		0x0276
#define ALIMIT_VAL_PEEP_NCPAP_16		0x0278
#define ALIMIT_STATE_PMAX_NCPAP_8		0x027A
#define ALIMIT_STATE_PEEP_NCPAP_8		0x027B


#define TRENDSCALE_RSBI_16				0x0290
#define TRENDSCALE_SHAREMVMAND_16		0x0292
#define TRENDSCALE_RESISTANCE_16		0x0294
#define TRENDSCALE_LEAK_16				0x0296
#define TRENDSCALE_SPO2_16				0x0298
#define TRENDSCALE_SPO2PI_16			0x029A
#define TRENDSCALE_ETCO2_16				0x029C
#define TRENDSCALE_SPO2PR_16				0x029E

#define PARA_ITIME_TRIGGER_16				0x02A0
#define PARA_ETIME_TRIGGER_16				0x02A2
#define PARA_BPM_TRIGGER_16					0x02A4
#define PARA_IFLOW_TRIGGER_16				0x02A6
#define PARA_EFLOW_TRIGGER_16				0x02A8
#define PARA_PEEP_TRIGGER_16				0x02AA
#define PARA_PINSP_TRIGGER_16				0x02AC
#define PARA_PMAXVOLG_TRIGGER_16			0x02AE
#define PARA_RISETIME_TRIGGER_16				0x02B0

#define PARA_VLIMIT_TRIGGER_16					0x02B2
#define PARA_VLIMITSTATE_TRIGGER_8				0x02B4
#define PARA_VGARANT_TRIGGER_16					0x02B5
#define PARA_VGARANTSTATE_TRIGGER_8				0x02B7

#define TRENDSCALE_FREQUENCY_16				0x02BA		

#define ALIMIT_VAL_ETCO2MAX_16			0x02C0
//#define ALIMIT_VAL_ETCO2MAX_VOL_16			0x02C0
//#define ALIMIT_VAL_ETCO2MAX_KPA_16			0x02C2
//#define ALIMIT_VAL_ETCO2MAX_MMHG_16			0x02C4
#define ALIMIT_VAL_ETCO2MIN_16			0x02C6
//#define ALIMIT_VAL_ETCO2MIN_VOL_16			0x02C6
//#define ALIMIT_VAL_ETCO2MIN_KPA_16			0x02C8
//#define ALIMIT_VAL_ETCO2MIN_MMHG_16			0x02CA
#define ALIMIT_STATE_ETCO2MAX_8			0x02CC
#define ALIMIT_STATE_ETCO2MIN_8			0x02CD

#define ALIMIT_VAL_ETCO2MAX_HF_16		0x02D0
//#define ALIMIT_VAL_ETCO2MAX_VOL_HF_16		0x02D0
//#define ALIMIT_VAL_ETCO2MAX_KPA_HF_16		0x02D2
//#define ALIMIT_VAL_ETCO2MAX_MMHG_HF_16		0x02D4
#define ALIMIT_VAL_ETCO2MIN_HF_16		0x02D6
//#define ALIMIT_VAL_ETCO2MIN_VOL_HF_16		0x02D6
//#define ALIMIT_VAL_ETCO2MIN_KPA_HF_16		0x02D8
//#define ALIMIT_VAL_ETCO2MIN_MMHG_HF_16		0x02DA
#define ALIMIT_STATE_ETCO2MAX_HF_8		0x02DC
#define ALIMIT_STATE_ETCO2MIN_HF_8		0x02DD


#define ALIMIT_VAL_FICO2MAX_16			0x02E0
//#define ALIMIT_VAL_FICO2MAX_VOL_16			0x02E0
//#define ALIMIT_VAL_FICO2MAX_KPA_16			0x02E2
//#define ALIMIT_VAL_FICO2MAX_MMHG_16			0x02E4
#define ALIMIT_VAL_FICO2MIN_16			0x02E6
//#define ALIMIT_VAL_FICO2MIN_VOL_16			0x02E6
//#define ALIMIT_VAL_FICO2MIN_KPA_16			0x02E8
//#define ALIMIT_VAL_FICO2MIN_MMHG_16			0x02EA
#define ALIMIT_STATE_FICO2MAX_8			0x02EC
#define ALIMIT_STATE_FICO2MIN_8			0x02ED

#define ALIMIT_VAL_FICO2MAX_HF_16		0x02F0
//#define ALIMIT_VAL_FICO2MAX_VOL_HF_16		0x02F0
//#define ALIMIT_VAL_FICO2MAX_KPA_HF_16		0x02F2
//#define ALIMIT_VAL_FICO2MAX_MMHG_HF_16		0x02F4
#define ALIMIT_VAL_FICO2MIN_HF_16		0x02F6
//#define ALIMIT_VAL_FICO2MIN_VOL_HF_16		0x02F6
//#define ALIMIT_VAL_FICO2MIN_KPA_HF_16		0x02F8
//#define ALIMIT_VAL_FICO2MIN_MMHG_HF_16		0x02FA
#define ALIMIT_STATE_FICO2MAX_HF_8		0x02FC
#define ALIMIT_STATE_FICO2MIN_HF_8		0x02FD

#define DEMO_FOT_DAY_8					0x02FE
#define DEMO_FOT_MONTH_8				0x02FF
#define DEMO_FOT_YEAR_16				0x0300

#define DEMO_HFO_DAY_8					0x0302
#define DEMO_HFO_MONTH_8				0x0303
#define DEMO_HFO_YEAR_16				0x0304

#define DEMO_NMODE_DAY_8				0x0306
#define DEMO_NMODE_MONTH_8				0x0307
#define DEMO_NMODE_YEAR_16				0x0308

#define DEMO_VGUARANTY_DAY_8			0x030A
#define DEMO_VGUARANTY_MONTH_8			0x030B
#define DEMO_VGUARANTY_YEAR_16			0x030C

#define DEMO_VLIMIT_DAY_8				0x030E
#define DEMO_VLIMIT_MONTH_8				0x030F
#define DEMO_VLIMIT_YEAR_16				0x0310

#define DEMO_LUNGREC_DAY_8				0x0312
#define DEMO_LUNGREC_MONTH_8			0x0313
#define DEMO_LUNGREC_YEAR_16			0x0314

#define DEMO_TREND_DAY_8				0x0316
#define DEMO_TREND_MONTH_8				0x0317
#define DEMO_TREND_YEAR_16				0x0318

#define DEMO_THERAPY_DAY_8				0x031A
#define DEMO_THERAPY_MONTH_8			0x031B
#define DEMO_THERAPY_YEAR_16			0x031C

#define DEMO_PRICO_DAY_8				0x031E
#define DEMO_PRICO_MONTH_8				0x031F
#define DEMO_PRICO_YEAR_16				0x0320

#define DEMO_NIVTRIGGER_DAY_8			0x0322
#define DEMO_NIVTRIGGER_MONTH_8			0x0323
#define DEMO_NIVTRIGGER_YEAR_16			0x0324
//letzte Adresse für Configuration 0x1EFB !!!!!!!!!!!!!!!!!!!!!!!
//ACHTUNG !!!!! wenn hier neue Daten eingefügt werden -> DefaultFactorySettings beachten!!!


/*****************************HARDWARE CONFIGURATION*****************************************/
//HARDWARE CONFIGURATION  !!!never delete!!!
#define HWCONF_SYSTEM				0x1EFF
#define TUBECONF					0x1F00
#define HWCONF_MAINBOARD			0x1F01
#define DEVICECONF					0x1F02
#define CO2CONFIG					0x1F03
#define PDMSCONFIG					0x1F04
#define ETHERNETPORT_16				0x1F05
#define SPO2CONFIG					0x1F07
#define FLOWSENSORCONF				0x1F08
#define AVREVISION					0x1F09
#define HFREVISION					0x1F0A
#define ACULINKVERSION				0x1F0B
//#define next						0x1F0C
// 
// Adressbereich 0x1EFF bis 0x1FFF ist für Hardware-Konfiguration reserviert, nicht löschen!!!!!
//
//
//
//letzte allgemeine Adresse 0x1FFF !!!!!!!!!!!!!!!!!!!!!!!



//!!!!!!!!!!!!!!!!!!!!!!!ACHTUNG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//wenn die Datei geändert wird unbedingt auch config.h von Projekt "FabianInstaller" und "Fabian" nachziehen
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


////////////////////////////////////////////////////////////////////////////////////////////////////
// End of config.h
////////////////////////////////////////////////////////////////////////////////////////////////////

