//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FabianHFO.rc
//
#define IDR_MAINFRAME                   128
#define IDR_FabianHFOTYPE               129
#define IDS_STRING129                   129
#define IDB_DTB_NUMHEADER               131
#define IDB_NUMPARA_1                   158
#define IDB_NUMPARA_2                   160
#define IDB_NUMPARA_3                   162
#define IDD_TLSMESSAGEBOX               164
#define IDB_EXCLAMATION                 169
#define IDB_CALSENSOR                   170
#define IDB_ALARMCLOCK_DW               188
#define IDB_ALARMCLOCK_FC               189
#define IDB_LIMIT_HIGH_DW               192
#define IDB_LIMIT_HIGH_FC               193
#define IDB_LIMIT_LOW_DW                195
#define IDB_BITMAP6                     196
#define IDB_LIMIT_LOW_FC                196
#define IDB_CLOCK_INACT_DW              198
#define IDB_CLOCK_INACT_FC              199
#define IDB_EXCLAMATION_RED             208
#define IDB_EXCLAMATION_BACK            209
#define IDB_PIC_SYSALARM                214
#define IDB_SYSAL_USE_ERROR             215
#define IDB_SYSAL_DEV_ERROR             216
#define IDB_ACLOCK_SYS_RED              217
#define IDB_ACLOCK_SYS_GREY             218
#define IDB_BTN_INFOTEXT                232
#define IDB_BTN_DATE_BAT                233
#define IDB_DTB_DATE_BAT                233
#define IDB_BTN_NUMERICSTATE            234
#define IDB_BTN_SUBPARA_DW1             235
#define IDB_BTN_SUBPARA_DW              235
#define IDB_BTN_SUBPARA_SIG1            236
#define IDB_BTN_SUBPARA_SIG             236
#define IDB_BTN_SUBPARA_UP1             237
#define IDB_BTN_SUBPARA_UP              237
#define IDB_BTN_4MENU_UP                241
#define IDB_BTN_4MENU_DW                242
#define IDB_SLIDER_NORMAL               264
#define IDB_SLIDER_ACTIVE               265
#define IDB_SLIDER_THUMB                266
#define IDB_SLIDER_THUMB_INACT          267
#define IDB_SLIDER_THUMB_ACT            268
#define IDB_BTN_SLIDER_R_UP             269
#define IDB_BITMAP3                     270
#define IDB_BTN_SLIDER_L_DW             270
#define IDB_BTN_SLIDER_L_UP             271
#define IDB_BTN_SLIDER_R_DW             272
#define IDB_BTN_NUM_BACK_UP             275
#define IDB_BTN_NUMERIC_DW              276
#define IDB_BTN_NUMERIC_UP              277
#define IDB_BTN_NUM_BACK_DW             278
#define IDB_BTN_SETUP_BOT_DW            279
#define IDB_BTN_SETUP_BOT_UP            280
#define IDB_BTN_SETUP_TOP_DW            281
#define IDB_BTN_SETUP_TOP_UP            282
#define IDB_BTN_SETUP1_UPUP             285
#define IDB_BTN_SETUP1_DWDW             290
#define IDB_BTN_SETUP1_DWUP             291
#define IDB_BTN_SETUP1_UPDW             292
#define IDB_BTN_SETUP_SEL               293
#define IDB_BTN_SETUP_FOC               294
#define IDB_BTN_SETUP_NOT               295
#define IDB_BTN_5MENU_ASILENT_UP        296
#define IDB_BTN_5MENU_ALOUD_DW          300
#define IDB_BTN_5MENU_ALOUD_UP          301
#define IDB_BTN_5MENU_AMEDIUM_DW        302
#define IDB_BTN_5MENU_AMEDIUM_UP        303
#define IDB_BTN_5MENU_AOFF_DW           304
#define IDB_BTN_5MENU_AOFF_UP           305
#define IDB_BTN_5MENU_ASILENT_DW        306
#define IDB_BTN_KBRD_ALPHANUM_UP        307
#define IDB_BTN_KBRD_ALPHANUM_DW        308
#define IDB_BTN_KBRD_SPACE_UP           309
#define IDB_BTN_KBRD_DEL_DW             310
#define IDB_BTN_KBRD_DEL_UP             311
#define IDB_BTN_KBRD_SHIFT_DW           312
#define IDB_BTN_KBRD_SHIFT_UP           313
#define IDB_BTN_KBRD_SPACE_DW           314
#define IDB_BITMAP1                     316
#define IDB_BTN_HEAD_ALIMIT             316
#define IDB_PARA_WARN_UP                325
#define IDB_PARA_KEY_DW                 326
#define IDB_PARA_WARN_DW                327
#define IDB_BTN_PARA_UP_TOP             328
#define IDB_BTN_PARA_DW_BOT             329
#define IDB_BTN_PARA_DW_TOP             330
#define IDB_BTN_PARA_UP_BOT             331
#define IDB_BTN_MONTH_UP                347
#define IDB_BTN_MONTH_DW                348
#define IDB_BTN_TIME_UP                 349
#define IDB_BTN_TIME_DW                 350
#define IDB_BTN_YEAR_UP                 351
#define IDB_BTN_MONTH_FC                353
#define IDB_BTN_TIME_FC                 354
#define IDB_OK_UP                       356
#define IDB_OK_DW                       357
#define IDB_OK_FC                       358
#define IDB_BTN_PARA_FC_TOP             359
#define IDB_BTN_PARA_FC_BOT             360
#define IDB_PARA_WARN_FC                361
#define IDB_GRAPH_CURSOR                364
#define IDB_EXCLAMATION_40x35           365
#define IDB_NUM_INFO_TOP                366
#define IDB_NUM_INFO_BOT                367
#define IDB_BTN_PAT_UP                  368
#define IDB_BTN_PAT_DW                  369
#define IDB_BTN_ALIMIT_UP               374
#define IDB_BTN_ALIMIT_DW               375
#define IDB_BTN_ALIMIT_FC               376
#define IDB_LIMIT_LOW_UP                377
#define IDB_ALARMCLOCK_UP               378
#define IDB_CLOCK_INACT_UP              379
#define IDB_LIMIT_HIGH_UP               380
#define IDB_LIMIT_LOW                   381
#define IDB_LIMIT_HIGH                  382
#define IDB_DTB_ASILENT_GREY            385
#define IDB_WARNING_GREY_23x20          386
#define IDB_BTN_PARA_SIG_BOT            388
#define IDB_BTN_SUBPARA_TRIG            389
#define IDB_PIC_ACULOGO                 390
#define IDB_PIC_FabianHFO               392
#define IDB_BTN_5MENU_DW                396
#define IDB_BTN_5MENU_FC                397
#define IDB_BTN_5MENU_UP                398
#define IDB_GRAPHBTN_ARW_UP             400
#define IDB_GRAPHBTN_ARW_DW             401
#define IDB_BTN_SETUP_OKGREENDW         402
#define IDB_BTN_SETUP_OKGREENUP         403
#define IDB_BTN_SETUP_OKREDDW           404
#define IDB_BTN_SETUP_OKREDUP           405
#define IDB_BTN_PAT_RED                 406
#define IDB_BTN_KBRD_DOWN_DW            407
#define IDB_BTN_KBRD_DOWN_UP            408
#define IDB_BTN_KBRD_LEFT_DW            409
#define IDB_BTN_KBRD_LEFT_UP            410
#define IDB_BTN_KBRD_RIGHT_DW           411
#define IDB_BITMAP9                     412
#define IDB_BTN_KBRD_RIGHT_UP           412
#define IDB_BTN_KBRD_UP_DW              413
#define IDB_BTN_KBRD_UP_UP              414
#define IDB_CURBTN_DOWN_DW              415
#define IDB_CURBTN_DOWN_UP              416
#define IDB_CURBTN_LEFT_DW              417
#define IDB_CURBTN_LEFT_UP              418
#define IDB_CURBTN_RIGHT_DW             419
#define IDB_CURBTN_RIGHT_UP             420
#define IDB_CURBTN_UP_DW                421
#define IDB_CURBTN_UP_UP                422
#define IDB_CURSOR_GRAPH                423
#define IDB_BTN_SETUP_TODAY_DW          424
#define IDB_BTN_SETUP_TODAY_UP          425
#define IDB_BTN_4MENU_DIS               426
#define IDB_BTN_PAT_BACK_DW             427
#define IDB_BTN_PAT_BACK_UP             428
#define IDB_BITMAP2                     429
#define IDB_BTN_VALV_DW                 429
#define IDB_BTN_VALV_UP                 430
#define IDB_BTN_5MENU_DECR_DW           431
#define IDB_BTN_5MENU_DECR_UP           432
#define IDB_BTN_5MENU_INCR_DW           433
#define IDB_BTN_5MENU_INCR_UP           434
#define IDB_BTN_5MENU_MOVEL_DW          435
#define IDB_BTN_5MENU_MOVEL_UP          436
#define IDB_BTN_5MENU_MOVER_DW          437
#define IDB_BTN_5MENU_MOVER_UP          438
#define IDB_BTN_PAT_DIS                 458
#define IDB_BTN_LEFT_DW                 459
#define IDB_BTN_LEFT_UP                 460
#define IDB_BTN_RIGHT_DW                461
#define IDB_BTN_RIGHT_UP                462
#define IDB_BTN_VALVOFF_DW              463
#define IDB_BTN_VALVOFF_UP              464
#define IDB_BTN_FG_DW                   465
#define IDB_BTN_FG_UP                   466
#define IDB_BTN_OPENCLOSE_DW            467
#define IDB_BTN_OPENCLOSE_UP            468
#define IDB_PATIENTDATA                 469
#define IDD_PASSWRD_DLG                 470
#define IDB_BTN_POPUP_DW                471
#define IDD_OXYCALMSG                   471
#define IDB_BTN_POPUP_UP                472
#define IDB_TIMEAXIS                    473
#define IDB_BATTERY_LOAD                474
#define IDB_SYSFAIL                     475
#define IDB_WARNING_RED_23x20           483
#define IDB_BTN_5MENU_DIS               484
#define IDB_PARA_WARN_SUB               485
#define IDB_ARROWDW_DW                  486
#define IDB_ARROWDW_FC                  487
#define IDB_ARROWDW_UP                  488
#define IDB_ARROWUP_DW                  489
#define IDB_ARROWUP_FC                  490
#define IDB_ARROWUP_UP                  491
#define IDB_BTN_GRAPHDW_DW              494
#define IDB_BTN_GRAPHDW_UP              495
#define IDB_BTN_GRAPHUP_DW              496
#define IDB_BTN_GRAPHUP_UP              497
#define IDB_BTN_DECREASE_DW             500
#define IDB_BTN_DECREASE_UP             501
#define IDB_BTN_INCREASE_DW             502
#define IDB_BTN_INCREASE_UP             503
#define IDB_BTN_PARA_SIG_BO             504
#define IDB_BTN_PARA_SIG_TOP            504
#define IDB_PARA_WARN_RED               505
#define IDB_ARROWDW_RED                 506
#define IDB_ARROWUP_RED                 507
#define IDB_DTB_NUMHEAD_ASILENT         509
#define IDB_DTB_ASILENT_YELLOW          510
#define IDB_PATIENTDATA_SETTING         511
#define IDB_MSG_CONFIG                  512
#define IDB_MSG_DELTREND                513
#define IDB_MSG_INFO                    514
#define IDB_MSG_STOP                    515
#define IDB_MSG_CAL0MBAR                516
#define IDB_MSG_CAL60MBAR               517
#define IDB_ALARMARROWDW_DW             518
#define IDB_ALARMARROWDW_FC             519
#define IDB_ALARMARROWDW_UP             520
#define IDB_ALARMARROWUP_DW             521
#define IDB_ALARMARROWUP_FC             522
#define IDB_ALARMARROWUP_UP             523
#define IDB_NUMALIMIT_1                 524
#define IDB_NUMALIMIT_2                 525
#define IDB_CURSOR_MOVEXSCALE           526
#define IDB_CURSOR_MOVEYSCALE           527
#define IDB_CURBTN_XDOWN_DW             528
#define IDB_CURBTN_XDOWN_UP             529
#define IDB_CURBTN_XUP_DW               530
#define IDB_CURBTN_XUP_UP               531
#define IDB_CURBTN_YLEFT_DW             532
#define IDB_CURBTN_YLEFT_UP             533
#define IDB_CURBTN_YRIGHT_DW            534
#define IDB_CURBTN_YRIGHT_UP            535
#define IDB_BTN_FACTORY_DW              550
#define IDB_BTN_FACTORY_UP              551
#define IDB_BTN_SCREENLOCK_DW           552
#define IDB_BTN_SCREENLOCK_UP           553
#define IDB_BTN_5MENU_REFRESH_DW        555
#define IDB_BITMAP5                     556
#define IDB_BTN_5MENU_REFRESH_UP        556
#define IDB_BTN_MOVEMENUL_DWN           566
#define IDB_BTN_MOVEMENUL_UP            567
#define IDB_BTN_MOVEMENUR_DWN           568
#define IDB_BTN_MOVEMENUR_UP            569
#define IDB_BTN_MOVEMENUL_DIS           570
#define IDB_BTN_MOVEMENUR_DIS           571
#define IDB_BTNMNU_CAL_DW               572
#define IDB_BTNMNU_CAL_UP               573
#define IDB_BTNMNU_DATE_DW              574
#define IDB_BTNMNU_DATE_UP              575
#define IDB_BTNMNU_DISPL_DW             576
#define IDB_BTNMNU_DISPL_UP             577
#define IDB_BTNMNU_HELP_DIS             578
#define IDB_BTNMNU_HELP_DW              579
#define IDB_BTNMNU_HELP_UP              580
#define IDB_BTNMNU_INFO_DW              581
#define IDB_BTNMNU_INFO_UP              582
#define IDB_BTNMNU_LANG_DW              583
#define IDB_BTNMNU_LANG_UP              584
#define IDB_BTNMNU_PAT_DW               585
#define IDB_BTNMNU_PAT_UP               586
#define IDB_BTNMNU_SERVICE_DW           587
#define IDB_BTNMNU_SERVICE_UP           588
#define IDB_BTNMNU_TOOLS_DW             589
#define IDB_BTNMNU_TOOLS_UP             590
#define IDB_BTNMNU_VENT_DW              591
#define IDB_BTNMNU_VENT_UP              592
#define IDB_BTNMNU_CAL_FC               593
#define IDB_BTNMNU_DATE_FC              594
#define IDB_BTNMNU_DISPL_FC             595
#define IDB_BTNMNU_HELP_FC              596
#define IDB_BTNMNU_INFO_FC              597
#define IDB_BTNMNU_LANG_FC              598
#define IDB_BTNMNU_PAT_FC               599
#define IDB_BTNMNU_SERVICE_FC           600
#define IDB_BTNMNU_TOOLS_FC             601
#define IDB_BTNMNU_VENT_FC              602
#define IDB_PIC_SHUTDOWN                603
#define IDB_BTN_CONTR_DW                604
#define IDB_BTN_CONTR_UP                605
#define IDB_BTN_DECRMAXCONTR_DW         606
#define IDB_BITMAP10                    607
#define IDB_BTN_DECRMAXCONTR_UP         607
#define IDB_BTN_INCRMAXCONTR_DW         610
#define IDB_BTN_INCRMAXCONTR_UP         611
#define IDB_SETUP_LE_BOT_CORNER         612
#define IDB_SETUP_LE_TOP_CORNER         613
#define IDB_SETUP_RI_BOT_CORNER         614
#define IDB_SETUP_RI_TOP_CORNER         615
#define IDB_SLD_CHAN_GREY               616
#define IDB_SLD_THUMB_ACT_GREY          617
#define IDB_SLD_THUMB_GREY              618
#define IDB_PIC_FILLED_GRAPH            619
#define IDB_PIC_NOTFIL_GRAPH            620
#define IDB_PIC_BRIGHTNESS1             621
#define IDB_PIC_BRIGHTNESS2             622
#define IDB_PIC_BRIGHTNESS3             623
#define IDB_PIC_BRIGHTNESS4             624
#define IDB_PIC_BRIGHTNESS5             625
#define IDB_PIC_NOAUTOSCALE             627
#define IDB_BTN_SCREENLOCKTIME_DIS      628
#define IDB_BTN_SCREENLOCKTIME_DW       629
#define IDB_BTN_SCREENLOCKTIME_FC       630
#define IDB_BTN_SCREENLOCKTIME_UP       631
#define IDB_BTN_BACKSET_DW              632
#define IDB_BTN_BACKSET_FC              633
#define IDB_BTN_BACKSET_UP              634
#define IDB_BTN_CALDISPLAY_DW           635
#define IDB_BTN_CALDISPLAY_UP           636
#define IDB_BTN_SETUPVENT_DW            638
#define IDB_BTN_SETUPVENT_FC            639
#define IDB_BTN_SETUPVENT_UP            640
#define IDB_BITMAP4                     641
#define IDB_OKSETTING_UP                641
#define IDB_BTN_SETUP_SETLANG_FOC       642
#define IDB_BTN_SETUP_SETLANG_NOT       643
#define IDB_BTN_SETUP_SETLANG_SEL       644
#define IDB_BTN_VALUE_DW                645
#define IDB_BTN_VALUE_FC                646
#define IDB_BTN_VALUE_UP                647
#define IDB_BTN_SETUP_DWDW              648
#define IDB_BTN_SETUP_DWFC              649
#define IDB_BTN_SETUP_DWUP              650
#define IDB_BTN_SETUP_UPDW              651
#define IDB_BTN_SETUP_UPFC              652
#define IDB_BTN_SETUP_UPUP              653
#define IDB_BTN_FACTORY_FC              654
#define IDB_BTNMNU_TOOLS_DIS            656
#define IDB_PIC_NEONATAL                657
#define IDB_PIC_PEDIATRIC               658
#define IDB_CLOCK_FACE_GREY             659
#define IDB_PIC_ACCU_0                  662
#define IDB_PIC_ACCU_20                 663
#define IDB_PIC_ACCU_40                 664
#define IDB_PIC_ACCU_60                 665
#define IDB_PIC_ACCU_80                 666
#define IDB_PIC_ACCU_100                667
#define IDB_PIC_ACCU_EMPTY              668
#define IDB_PIC_ACCU_EXTERN             669
#define IDB_PIC_ACCU_NET                670
#define IDB_PIC_ACCULOAD_0              671
#define IDB_BITMAP8                     672
#define IDB_PIC_ACCULOAD_20             672
#define IDB_PIC_ACCULOAD_40             673
#define IDB_PIC_ACCULOAD_60             674
#define IDB_PIC_ACCULOAD_80             675
#define IDB_PIC_ACCULOAD_100            676
#define IDB_BITMAP7                     677
#define IDB_PIC_NOMANATZ                677
#define IDB_PIC_NURSE32                 678
#define IDB_PIC_NURSEALARM              679
#define IDB_BTN160_LG_DIS               680
#define IDB_BTN160_LG_DW                681
#define IDB_BITMAP13                    682
#define IDB_BTN160_LG_UP                682
#define IDB_WAIT30_GREY1                683
#define IDB_WAIT30_GREY2                684
#define IDB_WAIT30_GREY3                685
#define IDB_WAIT30_GREY4                686
#define IDB_WAIT30_GREY5                687
#define IDB_WAIT30_GREY6                688
#define IDB_WAIT30_GREY7                689
#define IDB_WAIT30_GREY8                690
#define IDB_WAIT30_YEL1                 691
#define IDB_WAIT30_YEL2                 692
#define IDB_WAIT30_YEL3                 693
#define IDB_WAIT30_YEL4                 694
#define IDB_WAIT30_YEL5                 695
#define IDB_WAIT30_YEL6                 696
#define IDB_WAIT30_YEL7                 697
#define IDB_WAIT30_YEL8                 698
#define IDB_WAIT85_BLUE1                699
#define IDB_WAIT85_BLUE2                700
#define IDB_WAIT85_BLUE3                701
#define IDB_WAIT85_BLUE4                702
#define IDB_WAIT85_BLUE5                703
#define IDB_WAIT85_BLUE6                704
#define IDB_WAIT85_BLUE7                705
#define IDB_WAIT85_BLUE8                706
#define IDD_DIALOG1                     707
#define IDD_DLGACCUTEST                 707
#define IDB_BTNMNU_CO2_DIS              708
#define IDD_PASSWRD_DLG1                708
#define IDD_NUMINPUT_DLG                708
#define IDB_BTNMNU_CO2_DW               709
#define IDB_BTNMNU_CO2_FC               710
#define IDB_BTNMNU_CO2_UP               711
#define IDB_BTN_6MENU_DW                712
#define IDB_BTN_6MENU_UP                713
#define IDB_CO2PARA_LE                  714
#define IDB_CO2PARA_RI                  715
#define IDB_DTB_STARTHFO_GREY           717
#define IDB_DTB_STARTHFO_ALARM          718
#define IDB_DTB_STARTHFO_YELLOW         719
#define IDB_WARNING_BACKGRND            720
#define IDB_BTN_CALIBRATE_DW            721
#define IDB_BTN_CALIBRATE_FC            722
#define IDB_BTN_CALIBRATE_UP            723
#define IDB_BTN_6MENU_DIS               724
#define IDB_BTN_SETUPVENT_DIS           725
#define IDB_DTB_INFOLINE_GREY           726
#define IDB_DTB_INFOLINE_ORANGE         727
#define IDB_DTB_INFOLINE_RED            728
#define IDB_DTB_INFOLINE_SCREENLOCK     729
#define IDB_DTB_INFOLINE_YELLOW         730
#define IDB_DTB_STARTHFO_ORANGE         731
#define IDB_DTB_NUMHEAD_ALOG            732
#define IDB_BTN_HOSPITAL_DW             733
#define IDB_BTN_HOSPITAL_FC             734
#define IDB_BTN_HOSPITAL_UP             735
#define IDB_SELMENU_DIS                 737
#define IDB_SELMENU_DW                  738
#define IDB_SELMENU_FC                  739
#define IDB_SELMENU_UP                  740
#define IDB_BITMAP11                    744
#define IDB_ALARM_SIGNALED              744
#define IDB_MSG_HOSPITAL                745
#define IDB_NUMERIC_BOT                 746
#define IDB_NUMERIC_TOP                 747
#define IDB_FLOWMETER_LEFT              748
#define IDB_FLOWMETER_RIGHT             749
#define IDB_FLOWKEGEL_0                 750
#define IDB_FLOWKEGEL_1                 751
#define IDB_FLOWKEGEL_2                 752
#define IDB_FLOWKEGEL_3                 753
#define IDB_FLOWKEGEL_4                 754
#define IDB_FLOWKEGEL_5                 755
#define IDB_FLOWKEGEL_6                 756
#define IDB_FLOWKEGEL_7                 757
#define IDB_FLOWKEGEL_8                 758
#define IDB_FLOWKEGEL_9                 759
#define IDB_PIC_NIGHT                   760
#define IDB_MSG_USB                     761
#define IDB_PIC_MIXERALARM              762
#define IDB_PIC_MIXERSIGNAL             763
#define IDB_BTNMNU_VIDEO_DIS            764
#define IDB_BTNMNU_VIDEO_DW             765
#define IDB_BTNMNU_VIDEO_FC             766
#define IDB_BTNMNU_VIDEO_UP             767
#define IDB_PIC_NOVIDEO                 768
#define IDB_BTN_VIDEOPLAY_DW            769
#define IDB_BTN_VIDEOPLAY_UP            770
#define IDB_BTN_VIDEOSTOP_DW            771
#define IDB_BITMAP16                    772
#define IDB_BTN_VIDEOSTOP_UP            773
#define IDB_BTN_PARAMENU_DW             774
#define IDB_BITMAP14                    775
#define IDB_BTN_PARAMENU_UP             776
#define IDB_BTN_PARAMENUBCK_DW          777
#define IDB_BTN_PARAMENUBCK_UP          778
#define IDB_BTN_PARASET_DW_BOT          779
#define IDB_BTN_PARASET_DW_TOP          780
#define IDB_BTN_PARASET_FC_BOT          781
#define IDB_BTN_PARASET_FC_TOP          782
#define IDB_BTN_PARASET_UP_BOT          783
#define IDB_BTN_PARASET_UP_TOP          784
#define IDB_PCTRL_AUTOFLOW              785
#define IDB_PCTRL_IFLOW                 786
#define IDB_PCTRL_RAMPE                 787
#define IDB_BTN_SELMOD_BOT_DW           788
#define IDB_BTN_SELMOD_BOT_UP           789
#define IDB_BTN_SELMOD_MID_DW           790
#define IDB_BTN_SELMOD_MID_UP           791
#define IDB_BTN_SELMOD_TOP_DW           792
#define IDB_BTN_SELMOD_TOP_UP           793
#define IDB_BTN_SELVIEW_LE_DW           794
#define IDB_BTN_SELVIEW_LE_UP           795
#define IDB_BTN_SELVIEW_RI_DW           796
#define IDB_BTN_SELVIEW_RI_UP           797
#define IDC_BTN_CONFIGBORDER_BOT        798
#define IDC_BTN_CONFIGBORDER_LEFTBOTCORNER 799
#define IDC_BTN_CONFIGBORDER_TOP        800
#define IDB_BTN_CONFIG_CHANGEBOT_DW     801
#define IDB_BTN_CONFIG_CHANGEBOT_UP     802
#define IDB_PIC_CONFIG_CHANGE_DW        803
#define IDB_PIC_CONFIG_CHANGE_UP        804
#define IDB_BTN_CONFIG_CHANGETOP_DW     805
#define IDB_BTN_CONFIG_CHANGETOP_UP     806
#define IDB_BTN_SIZE_DW                 807
#define IDB_BTN_SIZE_UP                 808
#define IDB_BTN_CONFIG_NUM1_DW          809
#define IDB_BTN_CONFIG_NUM1_UP          810
#define IDB_BTN_CONFIG_NUM2_DW          811
#define IDB_BTN_CONFIG_NUM2_UP          812
#define IDB_BTN_CONFIG_NUM3_DW          813
#define IDB_BTN_CONFIG_NUM3_UP          814
#define IDB_BTN_CONFIG_NUM1_FC          815
#define IDB_BTN_CONFIG_NUM2_FC          816
#define IDB_BTN_CONFIG_NUM3_FC          817
#define IDB_DLG_BOT                     825
#define IDB_DLG_LEFT                    826
#define IDB_DLG_LEFT_BOT                827
#define IDB_DLG_LEFT_TOP                828
#define IDB_DLG_RIGHT                   829
#define IDB_DLG_RIGHT_BOT               830
#define IDB_DLG_RIGHT_TOP               831
#define IDB_DLG_TOP                     832
#define IDB_NEBULIZER                   833
#define IDB_NEBUL_BCKGD                 834
#define IDB_NEBUL_INFO                  835
#define IDB_WARNING_BCKG40              836
#define IDB_BTNMNU_NETWORK_DIS          837
#define IDB_BTNMNU_NETWORK_DW           838
#define IDB_BTNMNU_NETWORK_FC           839
#define IDB_BTNMNU_NETWORK_UP           840
#define IDB_BTN_WAVE_UP                 841
#define IDB_BTN_WAVE_FC                 842
#define IDB_BTN_WAVE_DW                 843
#define IDB_DTB_INFOLINE_GREY_DEMO      844
#define IDB_DTB_INFOLINE_ORANGE_DEMO    845
#define IDB_DTB_INFOLINE_RED_DEMO       846
#define IDB_DTB_INFOLINE_SCREENLOCK_DEMO 847
#define IDB_BITMAP19                    848
#define IDB_DTB_INFOLINE_YELLOW_DEMO    848
#define IDB_HELP_DW_BLUE                850
#define IDB_HELP_DW_DARKGREY            851
#define IDB_HELP_DW_LIGHTGREY           852
#define IDB_HELP_DW_YELLOW              853
#define IDB_HELP_UP_BLUE                854
#define IDB_HELP_UP_DARKGREY            855
#define IDB_HELP_UP_LIGHTGREY           856
#define IDB_HELP_UP_YELLOW              857
#define IDB_BTN6_YEL_DW                 860
#define IDB_BTN6_YEL_UP                 861
#define IDB_DTB_ALARMSILENT_GREY        862
#define IDB_DTB_ALARMSILENT_YELLOW      863
#define IDB_BTN_AUTOSET_DW              864
#define IDB_BTN_AUTOSET_UP              865
#define IDB_BITMAP12                    866
#define IDB_FLOWMETER_THERAPY           866
#define IDB_BITMAP15                    868
#define IDC_BTN_CONFIGBORDER_LEFT       868
#define IDB_BTN_SELMENU_DW              869
#define IDB_BTN_SELMENU_UP              870
#define IDB_BTN_SELMENU_BACK_DW         871
#define IDB_BTN_SELMENU_BACK_UP         872
#define IDB_BTN_POPUP_DIS               873
#define IDB_TRENDBTN_ARW_DW             874
#define IDB_PIC_AVCAL                   875
#define IDB_PIC_AVCALALARM              876
#define IDB_PIC_AVCALSIGNAL             877
#define IDB_BTN_7MENU_DIS               878
#define IDB_BTN_7MENU_DW                879
#define IDB_BITMAP20                    880
#define IDB_BTN_7MENU_UP                880
#define IDB_BTNMNU7_FREEZE_DIS          881
#define IDB_BTNMNU7_FREEZE_DWN          882
#define IDB_BTNMNU7_FREEZE_             883
#define IDB_BTNMNU7_FREEZE_UP           883
#define IDB_BTNMNU7_GRAPH_DIS           884
#define IDB_BTNMNU7_GRAPH_DWN           885
#define IDB_BTNMNU7_GRAPH_UP            886
#define IDB_BTNMNU7_LOOP_DIS            887
#define IDB_BTNMNU7_LOOP_DWN            888
#define IDB_BTNMNU7_LOOP_UP             889
#define IDB_BTNMNU7_SAVE_DIS            890
#define IDB_BTNMNU7_SAVE_DWN            891
#define IDB_BTNMNU7_SAVE_UP             892
#define IDB_BTNMNU7_TREND_DIS           893
#define IDB_BTNMNU7_TREND_DWN           894
#define IDB_BTNMNU7_TREND_UP            895
#define IDB_BTNMNU_SPO2_DIS             896
#define IDB_BTNMNU_SPO2_DW              897
#define IDB_BTNMNU_SPO2_FC              898
#define IDB_BTNMNU_SPO2_UP              899
#define IDB_BTN_ALIMITNUMERIC_DW        900
#define IDB_BTN_ALIMITNUMERIC_UP        901
#define IDB_NUM_TAU2                    902
#define IDB_BTN_SETUPVENTDIS_FC         903
#define IDB_BTN_SETUPVENTDIS_DW         904
#define IDB_NUM_TAU1                    905
#define IDB_BTN_NUMERIC3_DW             906
#define IDB_BITMAP21                    907
#define IDB_BTN_NUMERIC3_UP             907
#define IDB_BTNPOPUP_LOOP_DIS           908
#define IDB_BTNPOPUP_LOOP_DW            909
#define IDB_BTNPOPUP_LOOP_UP            910
#define IDB_BTNPOPUP_TRD_DIS            911
#define IDB_BTNPOPUP_TRD_DW             912
#define IDB_BTNPOPUP_TRD_UP             913
#define IDB_BTNPOPUP_WAV_DIS            914
#define IDB_BTNPOPUP_WAV_DW             915
#define IDB_BTNPOPUP_WAV_UP             916
#define IDB_BTN_GRAPH_UP1               917
#define IDB_BTN_PARA_ONOFF_UP           918
#define IDB_BITMAP18                    919
#define IDB_BTN_PARA_ONOFF_DW           919
#define IDB_BITMAP17                    920
#define IDB_BTN_SELSETTING_DW           921
#define IDB_BITMAP23                    922
#define IDB_BTN_SELSETTING_UP           922
#define IDB_BTN_SELSETTING_FC           924
#define IDB_BITMAP22                    925
#define IDB_BTN_PARA_DIS_BOT            925
#define IDB_PIC_GROUP_BOT               926
#define IDB_PIC_GROUP_TOP_BOT           927
#define IDB_BTN_GROUP_DW_BOT            928
#define IDB_BTN_GROUP_DW_TOP            929
#define IDB_BTN_GROUP_FC_BOT            930
#define IDB_BTN_GROUP_FC_TOP            931
#define IDB_BTN_GROUP_SIG_BOT           932
#define IDB_BTN_GROUP_SIG_TOP           933
#define IDB_BTN_GROUP_UP_BOT            934
#define IDB_BITMAP31                    935
#define IDB_BTN_GROUP_UP_TOP            935
#define IDB_BTN_SELECT_YES              936
#define IDB_BITMAP25                    937
#define IDB_BTN_SELECT_NO               937
#define IDB_BTN_PARA_DIS_TOP            938
#define IDB_BITMAP26                    939
#define IDB_PARA_WARN_DIS               939
#define IDB_BITMAP24                    940
#define IDB_ARROWUP_GREY                940
#define IDB_BITMAP27                    941
#define IDB_EXCLAMATION_LGHTGREY        941
#define IDB_BTN_SETPED_DW               942
#define IDB_BTN_SETPED_FC               943
#define IDB_BTN_SETPED_UP               944
#define IDB_BTN_SETNEO_DW               945
#define IDB_BTN_SETNEO_FC               946
#define IDB_BTN_SETNEO_UP               947
#define IDB_BTNMNU_O2_DIS               948
#define IDB_BTNMNU_O2_DW                949
#define IDB_BTNMNU_O2_FC                950
#define IDB_BITMAP32                    951
#define IDB_BTNMNU_O2_UP                951
#define IDB_BTN_DELAYVALUE_DW           952
#define IDB_BTN_DELAYVALUE_FC           953
#define IDB_BITMAP30                    954
#define IDB_BTN_DELAYVALUE_UP           954
#define IDB_SPO2PARA_LE_TOP             955
#define IDB_SPO2PARA_RI_TOP             956
#define IDB_SPO2PARA_LE_BOT             957
#define IDB_SPO2PARA_RI_BOT             958
#define IDB_BTN_ONOFF_DW                959
#define IDB_BTN_ONOFF_UP                960
#define IDB_PIC_PRICO_1                 961
#define IDB_PIC_PRICO_2                 962
#define IDB_PIC_PRICO_3                 963
#define IDB_PIC_PRICO_4                 964
#define IDB_PIC_PRICO_5                 965
#define IDB_PIC_PRICO_6                 966
#define IDB_PIC_PRICO_7                 967
#define IDB_PIC_PRICO_8                 968
#define IDB_PIC_PRICO_9                 969
#define IDB_PIC_PRICO_10                970
#define IDB_PIC_PRICO_11                971
#define IDB_PIC_PRICO_12                972
#define IDB_PIC_PRICO_13                973
#define IDB_PIC_PRICO_14                974
#define IDB_PIC_PRICO_15                975
#define IDB_PIC_PRICO_16                976
#define IDB_PIC_PRICO_17                977
#define IDB_PIC_PRICO_18                978
#define IDB_PIC_PRICO_19                979
#define IDB_PIC_PRICO_20                980
#define IDB_PIC_PRICO_21                981
#define IDB_PIC_PRICO_22                982
#define IDB_PIC_PRICO_23                983
#define IDB_PIC_PRICO_24                984
#define IDB_FRAME_SIQ                   985
#define IDB_BTN_PRICOLIMIT_LE_DW        986
#define IDB_BTN_PRICOLIMIT_LE_UP        987
#define IDB_BTN_PRICOLIMIT_RI_DW        988
#define IDB_BTN_PRICOLIMIT_RI_UP        989
#define IDB_BTN_ONOFF_DIS               990
#define IDB_PIC_MAINTENANCE             991
#define IDB_BITMAP29                    992
#define IDB_BTN_SETUP_OK_DIS            992
#define IDD_DLGPROXP60CAL               993
#define IDB_BITMAP28                    994
#define IDB_BTN_SELSETTING_DIS          994
#define IDB_FOT_DECREASE_DIS            995
#define IDB_FOT_DECREASE_DW             996
#define IDB_FOT_DECREASE_UP             997
#define IDB_FOT_REPEAT_DIS              998
#define IDB_FOT_REPEAT_DW               999
#define IDC_CALIBRATION                 1000
#define IDB_FOT_REPEAT_UP               1000
#define IDB_FOT_RUN_DIS                 1001
#define IDC_RETRY                       1002
#define IDB_FOT_RUN_DW                  1002
#define IDC_TEXTMSG                     1003
#define IDB_FOT_RUN_UP                  1003
#define IDC_ONOFF                       1004
#define IDC_RUN                         1004
#define IDC_FREE                        1004
#define IDB_FOT_ONOFF_DIS               1004
#define IDC_RUNSTOP                     1005
#define IDC_ON                          1005
#define IDB_FOT_ONOFF_DW                1005
#define IDC_MENU1                       1006
#define IDB_BITMAP44                    1006
#define IDB_FOT_ONOFF_UP                1006
#define IDC_MENU2                       1007
#define IDB_BITMAP33                    1007
#define IDB_BTN_SETPED_DIS              1007
#define IDC_MENU3                       1008
#define IDB_BITMAP34                    1008
#define IDB_BTN_PARASET_DIS_BOT         1008
#define IDC_MENU4                       1009
#define IDC_MENU5                       1010
#define IDC_MENU8                       1013
#define IDC_RETURN                      1013
#define IDC_MINUS                       1014
#define IDC_PLUS                        1015
#define IDC_O2                          1016
#define IDC_SYSALARM                    1018
#define IDC_BUTTON1                     1026
#define IDC_EDIT1                       1027
#define IDC_INFOTXT                     1028
#define IDC_BUTTON2                     1029
#define IDC_BTN_OXY0                    1029
#define IDC_BUTTON3                     1030
#define IDC_BTN_OXY60                   1030
#define IDC_BUTTON4                     1031
#define IDC_PICTURE                     1031
#define IDC_BUTTON5                     1032
#define IDC_CALPIC                      1032
#define IDC_BUTTON6                     1033
#define IDC_PROXCAL_PRESSURE            1033
#define IDC_BUTTON7                     1034
#define IDC_PROXCAL_PROXADC             1034
#define IDC_BUTTON8                     1035
#define IDC_BUTTON9                     1036
#define IDC_BUTTON10                    1037
#define IDC_BUTTON0                     1037
#define IDC_BUTTON_C                    1038
#define IDC_BUTTON_DEL                  1038
#define IDC_BUTTONA                     1039
#define IDC_BUTTONB                     1040
#define IDC_BUTTONC                     1041
#define IDC_BUTTOND                     1042
#define IDC_BUTTONE                     1043
#define IDC_BUTTONF                     1044
#define IDC_STATICPWDLG                 1045
#define IDC_STATICPWDLG2                1046
#define IDC_TXTCAPTION                  1046
#define IDC_PRESSURE                    1048
#define IDC_EDIT2                       1049
#define IDC_PROXADC                     1049
#define IDC_EDIT3                       1050
#define IDC_EDIT4                       1051
#define IDC_EDIT5                       1052
#define IDS_LANGPATH                    10000
#define IDS_CURLANGUAGE                 10001
#define IDS_LANGID                      10002
#define IDS_VERSION_LANGUAGE            10003
#define IDS_IPPV                        10031
#define IDS_SIPPV                       10032
#define IDS_SIMV                        10033
#define IDS_SIMVPSV                     10034
#define IDS_PSV                         10035
#define IDS_CPAP                        10036
#define IDS_NCPAP                       10037
#define IDS_DUOPAP                      10038
#define IDS_HFO                         10039
#define IDS_IPPV_PRE                    10040
#define IDS_SIPPV_PRE                   10041
#define IDS_SIMV_PRE                    10042
#define IDS_SIMVPSV_PRE                 10043
#define IDS_PSV_PRE                     10044
#define IDS_HFO_PRE                     10045
#define IDS_CPAP_PRE                    10046
#define IDS_NCPAP_PRE                   10047
#define IDS_DUOPAP_PRE                  10048
#define IDS_SERVICE                     10050
#define IDS_SYSALARM                    10051
#define IDS_STANDBY                     10052
#define IDS_EXHALVALV_CAL               10053
#define IDS_O2THERAPIE                  10054
#define IDS_THERAPIE_PRE                10055
#define IDS_MENU_LANGUAGE               10100
#define IDS_MENU_DATETIME               10101
#define IDS_MENU_SETTINGS               10102
#define IDS_MENU_PATIENT                10103
#define IDS_MENU_SYSTEM                 10104
#define IDS_MENU_AUTOSET                10105
#define IDS_MENU_ALL                    10106
#define IDS_MENU_SINGLE                 10107
#define IDS_MENU_SHOWLOG                10108
#define IDS_MENU_CLOSELOG               10109
#define IDS_MENU_CURVES                 10110
#define IDS_MENU_LOOPS                  10111
#define IDS_MENU_FREEZE                 10112
#define IDS_MENU_SAVE                   10113
#define IDS_MENU_CONTINUE               10114
#define IDS_MENU_OPEN_TOP               10114
#define IDS_MENU_FLOWKORR               10115
#define IDS_MENU_OPEN_BOT               10115
#define IDS_MENU_MBAR                   10116
#define IDS_MENU_CLOSE_TOP              10116
#define IDS_MENU_SYSCAL                 10117
#define IDS_MENU_CLOSE_BOT              10117
#define IDS_MENU_CAL1                   10118
#define IDS_MENU_CAL2                   10119
#define IDS_MENU_CAL3                   10120
#define IDS_MENU_CAL4                   10121
#define IDS_MENU_CAL5                   10122
#define IDS_MENU_CAL6                   10123
#define IDS_MENU_CAL7                   10124
#define IDS_MENU_CAL8                   10125
#define IDS_MENU_O2CAL                  10126
#define IDS_MENU_FLOWCAL                10127
#define IDS_MENU_ALARM                  10128
#define IDS_MENU_RESET                  10129
#define IDS_MENU_TREND                  10130
#define IDS_MENU_FLOWCAL_INT_TOP        10131
#define IDS_MENU_FLOWCAL_INT_BOT        10132
#define IDS_MENU_FLOWCAL_EXT_TOP        10133
#define IDS_MENU_FLOWCAL_EXT_BOT        10134
#define IDS_MENU_CO2                    10135
#define IDS_MENU_CONTROLLED             10136
#define IDS_MENU_TRIGGER                10137
#define IDS_MENU_NMODE                  10138
#define IDS_MENU_MAINBOARD              10139
#define IDS_MENU_SPO2                   10144
#define IDS_MENU_FOT                    10145
#define IDS_MENU_ALIMIT_SPO2            10146
#define IDS_MENU_ALIMIT_CO2             10147
#define IDS_MENU_ALIMIT_VENT            10148
#define IDS_UNIT_MBAR                   10150
#define IDS_UNIT_OVERPEEP               10151
#define IDS_UNIT_LITER                  10152
#define IDS_UNIT_BPM                    10153
#define IDS_UNIT_PERCENT                10154
#define IDS_UNIT_SECONDS                10155
#define IDS_UNIT_LPM                    10156
#define IDS_UNIT_MILLILITER             10157
#define IDS_UNIT_LMIN                   10158
#define IDS_UNIT_HZ                     10159
#define IDS_UNIT_ML2SEC                 10160
#define IDS_UNIT_CMH2O                  10160
#define IDS_UNIT_1PERMIN                10161
#define IDS_UNIT_MLMBAR                 10162
#define IDS_UNIT_MBARLPS                10163
#define IDS_UNIT_MLSEC                  10164
#define IDS_UNIT_HRS                    10165
#define IDS_UNIT_MIN                    10166
#define IDS_UNIT_MMHG                   10167
#define IDS_UNIT_KPA                    10168
#define IDS_UNIT_VOLPERCENT             10169
#define IDS_UNIT_MLCMH2O                10170
#define IDS_UNIT_CMH2OLPS               10171
#define IDS_UNIT_DUO_BPM                10172
#define IDS_UNIT_MLLPS                  10173
#define IDS_ALARM_IF_PIF                10200
#define IDS_ALARM_DISCONNECTION         10201
#define IDS_ALARM_PO2IN                 10202
#define IDS_ALARM_PAIRIN                10203
#define IDS_ALARM_TUBEEXSP              10204
#define IDS_ALARM_TUBEINSP              10205
#define IDS_ALARM_FLOWSENSOR_DEFECT     10206
#define IDS_ALARM_FLOWSENSOR_CLEAN      10207
#define IDS_ALARM_FLOWSENSOR_NOTCON     10208
#define IDS_ALARM_O2SENSOR_DEFECT       10209
#define IDS_ALARM_O2SENSOR_USED         10210
#define IDS_ALARM_O2VALUE               10211
#define IDS_ALARM_RELAIS_DEFECT         10212
#define IDS_ALARM_PPROXIMAL             10213
#define IDS_ALARM_PIN_MIXER             10214
#define IDS_ALARM_OVERPRESSURE          10215
#define IDS_ALARM_VOLTAGE               10216
#define IDS_ALARM_IF_TERM               10217
#define IDS_ALARM_IE2                   10218
#define IDS_ALARM_BACKUP_ACTIVE         10218
#define IDS_ALARM_MVMAX                 10219
#define IDS_ALARM_MVMIN                 10220
#define IDS_ALARM_PMAX                  10221
#define IDS_ALARM_PMIN                  10222
#define IDS_ALARM_BPMMAX                10223
#define IDS_ALARM_LEAKMAX               10224
#define IDS_ALARM_APNOE                 10225
#define IDS_ALARM_O2SENSOR              10226
#define IDS_ALARM_INTERNALERROR         10227
#define IDS_ALARM_REL                   10228
#define IDS_ALARM_DCO2_HI               10228
#define IDS_ALARM_DC                    10229
#define IDS_ALARM_DCO2_LO               10229
#define IDS_ALARM_AIR                   10230
#define IDS_ALARM_OXY                   10231
#define IDS_ALARM_BLENDER               10232
#define IDS_ALARM_CPU                   10233
#define IDS_ALARM_IF_CO2                10233
#define IDS_ALARM_PINSP_NOTREACH        10234
#define IDS_ALARM_VLIMIT                10235
#define IDS_ALARM_TUBUSBLOCK            10236
#define IDS_ALARM_SYSAL                 10237
#define IDS_ALARM_AKKU60                10238
#define IDS_ALARM_AKKU30                10239
#define IDS_ALARM_AKKU15                10240
#define IDS_ALARM_POWERFAIL             10241
#define IDS_ALARM_IF_TERMINAL           10242
#define IDS_ALARM_O2CALERROR            10243
#define IDS_ALARM_CSCONPIC              10244
#define IDS_ALARM_CSMONPIC              10245
#define IDS_ALARM_IF_SPI                10246
#define IDS_ALARM_IF_DIO                10247
#define IDS_ALARM_IF_COM                10248
#define IDS_ALARM_IF_I2C                10249
#define IDC_ALARM_IF_I2C                10249
#define IDS_ALARM_OUTOFMEMORY           10250
#define IDS_ALARM_VGARANTY              10251
#define IDS_ALARM_FAN                   10252
#define IDS_ALARM_ETCO2_HI              10253
#define IDS_ALARM_ETCO2_LO              10254
#define IDS_ALARM_PMIN_HIGH             10255
#define IDS_ALARM_MIXER                 10256
#define IDS_ALARM_NEBUL_DISCON          10257
#define IDS_ALARM_NEBUL_ERROR           10258
#define IDS_ALARM_CO2_MODULE_NOTCONNECTED 10259
#define IDS_ALARM_CO2_FILTERLINE_NOTCONNECTED 10260
#define IDS_ALARM_CO2_CHECKSAMPLINGLINE 10261
#define IDS_ALARM_CO2_CHECKAIRWAYADAPTER 10262
#define IDS_ALARM_CO2_SENSORFAULTY      10263
#define IDS_ALARM_CO2_OCCLUSION         10264
#define IDS_ALARM_VGARANTY_HI           10265
#define IDS_ALARM_TUBE_OCCLUSION        10266
#define IDS_ALARM_APNEAVENT_ACTIVE      10267
#define IDS_ALARM_SPO2_MODULE_NOTCONNECTED 10268
#define IDS_ALARM_SPO2_SENSORFAULTY     10269
#define IDS_ALARM_SPO2_CHECKSENSOR      10270
#define IDS_ALARM_SPO2_HI               10271
#define IDS_ALARM_SPO2_LO               10272
#define IDS_ALARM_PULSERATE_HI          10273
#define IDS_ALARM_PULSERATE_LO          10274
#define IDS_ALARM_SPO2_PI_LO            10275
#define IDS_ALARM_PRESSURE_NOTREACH     10276
#define IDS_ALARM_FICO2_HI              10277
#define IDS_ALARM_FICO2_LO              10278
#define IDS_ALARM_PRICOFIO2             10279
#define IDS_ALARM_FIO2MAX               10279
#define IDS_ALARM_PRICOSPO2             10280
#define IDS_ALARM_FIO2MIN               10280
#define IDS_ALARM_PRICOSIQ              10281
#define IDS_ALARM_PIPMIN                10282
#define IDS_ALARM_PMAX_CPAP             10283
#define IDS_PARA_MV                     10300
#define IDS_PARA_PMAX                   10301
#define IDS_PARA_PEEP                   10302
#define IDS_PARA_FREQ                   10303
#define IDS_PARA_LEAK                   10304
#define IDS_PARA_APNOE                  10305
#define IDS_PARA_P                      10306
#define IDS_PARA_MAX                    10307
#define IDS_PARA_T                      10308
#define IDS_PARA_TE                     10309
#define IDS_PARA_INSPIRATION            10310
#define IDS_PARA_EXPIRATION             10311
#define IDS_PARA_MITT                   10312
#define IDS_PARA_HFO                    10313
#define IDS_PARA_AMPL                   10314
#define IDS_PARA_DEMFLOW                10315
#define IDS_PARA_GES                    10316
#define IDS_PARA_RESP                   10317
#define IDS_PARA_PROZANTEIL             10318
#define IDS_PARA_PAT                    10319
#define IDS_PARA_IFLOW                  10320
#define IDS_PARA_EFLOW                  10321
#define IDS_PARA_FLOW                   10322
#define IDS_PARA_MIN                    10323
#define IDS_PARA_HF                     10324
#define IDS_PARA_CPAP                   10325
#define IDS_PARA_INSP                   10326
#define IDS_PARA_DUO                    10327
#define IDS_PARA_PSV                    10328
#define IDS_PARA_V                      10329
#define IDS_PARA_LIMIT                  10330
#define IDS_PARA_GARANT                 10331
#define IDS_PARA_TRIGGER                10332
#define IDS_PARA_ITIME                  10333
#define IDS_PARA_BACKUP                 10334
#define IDS_PARA_ETIME                  10335
#define IDS_PARA_PLATEAU                10336
#define IDS_PARA_TRIGVOL                10337
#define IDS_PARA_IE                     10338
#define IDS_PARA_REC                    10339
#define IDS_PARA_C                      10340
#define IDS_PARA_R                      10341
#define IDS_PARA_EXP                    10343
#define IDS_PARA_TRIGFLOW               10344
#define IDS_PARA_MANUAL                 10345
#define IDS_PARA_TI                     10346
#define IDS_PARA_ACRITPSV_TOP           10347
#define IDS_PARA_ACRITPSV_BOT           10348
#define IDS_PARA_MANBREATHTIME_TOP      10349
#define IDS_PARA_MANBREATHTIME_BOT      10350
#define IDS_PARA_PRESSURERISE_TOP       10351
#define IDS_PARA_PRESSURERISE_BOT       10352
#define IDS_PARA_AUTOFLOW               10353
#define IDS_PARA_RAMP                   10354
#define IDS_PARA_PSVTIME                10355
#define IDS_PARA_DUOFREQ                10356
#define IDS_PARA_HF_FREQ                10357
#define IDS_PARA_CO2FREQ                10358
#define IDS_PARA_FLUSH                  10359
#define IDS_PARA_O2                     10360
#define IDS_PARA_DUO_ITIME              10361
#define IDS_PARA_DUO_ETIME              10362
#define IDS_PARA_DUO_CPAP               10363
#define IDS_PARA_DUO_MAX                10364
#define IDS_PARA_DUO_PEEP               10365
#define IDS_PARA_HF_AMP                 10366
#define IDS_PARA_HFFREQ_NOTE            10367
#define IDS_PARA_HFO_AMP                10368
#define IDS_PARA_ETCO                   10369
#define IDS_PARA_HFO_FREQ               10370
#define IDS_PARA_DUO_P                  10371
#define IDS_PARA_DUO_PEEP_NOTE          10372
#define IDS_PARA_PROZENT                10373
#define IDS_PARA_SPO2_PI                10374
#define IDS_PARA_SPO2_PULSERATE         10375
#define IDS_PARA_TAU                    10376
#define IDS_PARA_RSBI                   10377
#define IDS_PARA_SPO2_PR                10378
#define IDS_PARA_PIP                    10379
#define IDS_PARA_FICO                   10380
#define IDS_PARA_RISETIME               10381
#define IDS_PARA_LEAKCOMP               10382
#define IDS_PARA_FREQBACKUP             10383
#define IDS_PARA_VTEKG                  10384
#define IDS_PARA_VTEHFOKG               10385
#define IDS_BTN_SELPRESSUREGRAPH        10400
#define IDS_BTN_SELFLOWGRAPH            10401
#define IDS_BTN_SELVOLUMEGRAPH          10402
#define IDS_BTN_NUMERICS                10403
#define IDS_BTN_SCREENLOCK              10403
#define IDS_BTN_CALIBRATION             10404
#define IDS_BTN_SAVE                    10405
#define IDS_BTN_START                   10406
#define IDS_BTN_OK                      10407
#define IDS_BTN_CANCEL                  10408
#define IDS_BTN_SYNCCURSOR_TOP          10409
#define IDS_BTN_SYNCCURSOR_BOTTOM       10410
#define IDS_BTN_DEFAULTS                10411
#define IDS_BTN_MNU_CAL                 10412
#define IDS_BTN_MNU_DIS                 10413
#define IDS_BTN_MNU_VENT                10414
#define IDS_BTN_MNU_PAT                 10415
#define IDS_BTN_MNU_LANG                10416
#define IDS_BTN_MNU_DATETIME            10417
#define IDS_BTN_MNU_INFO                10418
#define IDS_BTN_MNU_SERVICE             10419
#define IDS_BTN_MNU_TOOLS               10420
#define IDS_BTN_MNU_HELP                10421
#define IDS_BTN_MNU_CO2                 10422
#define IDS_BTN_HOSPITALSET             10423
#define IDS_BTN_MNU_VIDEO               10424
#define IDS_BTN_MNU_PDMS                10425
#define IDS_BTN_MNU_SPO2                10426
#define IDS_BTN_BIAS_INT1               10427
#define IDS_BTN_BIAS_INT2               10428
#define IDS_BTN_BIAS_EXT1               10429
#define IDS_BTN_BIAS_EXT2               10430
#define IDS_BTN_VG1                     10431
#define IDS_BTN_VG2                     10432
#define IDS_BTN_VL1                     10433
#define IDS_BTN_VL2                     10434
#define IDS_BTN_CONFIRM                 10435
#define IDS_BTN_MNU_O2                  10436
#define IDS_BTN_PRESSURERISE            10437
#define IDS_GRAPH_PRESSURE              10500
#define IDS_GRAPH_VOLUME                10501
#define IDS_GRAPH_FLOW                  10502
#define IDS_COM_ERROR                   10600
#define IDS_COM_CHKSUM_ERROR            10601
#define IDS_COM_CHKSUM                  10602
#define IDS_TXT_AUTO                    10700
#define IDS_TXT_OFF                     10701
#define IDS_TXT_ENDRANGE                10702
#define IDS_TXT_LIMITTED                10703
#define IDS_TXT_ALIMITS                 10704
#define IDS_TXT_CHCKSENSOR              10705
#define IDS_TXT_CALCNCL                 10706
#define IDS_TXT_CALRUNNING              10707
#define IDS_TXT_CALIBRATED              10708
#define IDS_TXT_SENSOROFF               10709
#define IDS_TXT_SENSORON                10710
#define IDS_TXT_CONNECTED               10711
#define IDS_TXT_NOTCONNECTED            10712
#define IDS_TXT_AVERAGE                 10713
#define IDS_TXT_AUTOCAL_OXY             10713
#define IDS_TXT_BTB                     10714
#define IDS_TXT_21PERC                  10714
#define IDS_TXT_BEDIENFEHLER            10715
#define IDS_TXT_21_100PERC              10715
#define IDS_TXT_DEVERROR                10716
#define IDS_TXT_SCREENLOCK              10716
#define IDS_TXT_FLOWSENSOR              10717
#define IDS_TXT_O2SENSOR                10718
#define IDS_TXT_JANUARY                 10719
#define IDS_TXT_FEBRUARY                10720
#define IDS_TXT_MARCH                   10721
#define IDS_TXT_APRIL                   10722
#define IDS_TXT_MAY                     10723
#define IDS_TXT_JUNE                    10724
#define IDS_TXT_JULY                    10725
#define IDS_TXT_AUGUST                  10726
#define IDS_TXT_SEPTEMBER               10727
#define IDS_TXT_OCTOBER                 10728
#define IDS_TXT_NOVEMBER                10729
#define IDS_TXT_DECEMBER                10730
#define IDS_TXT_RANGE                   10738
#define IDS_TXT_PEDIATRIC               10739
#define IDS_TXT_NEONATAL                10740
#define IDS_TXT_RATIOITIME              10741
#define IDS_TXT_BPMITIME                10742
#define IDS_TXT_ITIMEETIME              10743
#define IDS_TXT_SETUPAUTOSCALE          10744
#define IDS_TXT_SETUPAUTOSCALE_GRAPH    10744
#define IDS_TXT_FLOWSENSOR_OFF          10745
#define IDS_TXT_ON                      10746
#define IDS_TXT_GRAPHDISPL              10747
#define IDS_TXT_FILLED                  10748
#define IDS_TXT_NOTFILLED               10749
#define IDS_TXT_AUTOSCALE               10750
#define IDS_TXT_FLUSHTIME               10751
#define IDS_TXT_NTPD                    10752
#define IDS_TXT_BTPS                    10753
#define IDS_TXT_REFFLOWSENSOR           10754
#define IDS_TXT_REF                     10755
#define IDS_TXT_FLOWOFF                 10756
#define IDS_TXT_AUTOSCREENLOCK          10756
#define IDS_TXT_O2OFF                   10757
#define IDS_TXT_LOADLANG                10757
#define IDS_TXT_RESPIR_STOPPED          10758
#define IDS_TXT_FLOWO2                  10759
#define IDS_TXT_WARN_MEDIJET            10760
#define IDS_TXT_WARN_INFANTFLOW         10761
#define IDS_TXT_WARN_INFANTFLOWLP       10762
#define IDS_TXT_NOTACTIVE               10763
#define IDS_TXT_NAME                    10764
#define IDS_TXT_FIRSTNAME               10765
#define IDS_TXT_PERSID                  10766
#define IDS_TXT_BIRTH                   10767
#define IDS_TXT_WEIGHT                  10768
#define IDS_TXT_DDMMYY                  10769
#define IDS_TXT_RESET                   10770
#define IDS_TXT_APPLY                   10771
#define IDS_TXT_ASKPATDATA              10772
#define IDS_TXT_ASKSTARTUP              10773
#define IDS_TXT_ASKNOTSTARTUP           10774
#define IDS_TXT_RESPSTOP_TOP            10775
#define IDS_TXT_SHUTDOWN                10775
#define IDS_TXT_RESPSTOP_BOT            10776
#define IDS_TXT_WARNNOPSWRD             10776
#define IDS_TXT_SELFTEST                10777
#define IDS_TXT_TRIGMODE                10778
#define IDS_TXT_VOLTRIGGER              10779
#define IDS_TXT_FLOWTRIGGER             10780
#define IDS_TXT_TODAY                   10781
#define IDS_TXT_MANBREATHTIME           10782
#define IDS_TXT_CHANGE                  10783
#define IDS_TXT_PATDATA                 10784
#define IDS_TXT_CAL_NOTPOSSIBLE         10784
#define IDS_TXT_REMARK                  10785
#define IDS_TXT_PATDATASAVE             10786
#define IDS_TXT_CANCEL                  10787
#define IDS_TXT_STARTVENT               10788
#define IDS_TXT_SYSINF                  10789
#define IDS_TXT_OPDEV                   10790
#define IDS_TXT_OPACCU                  10791
#define IDS_TXT_DEVID                   10792
#define IDS_TXT_SOFTVERS                10793
#define IDS_TXT_MONPICVERS              10794
#define IDS_TXT_CONPICVERS              10795
#define IDS_TXT_BRIGHTNESS              10796
#define IDS_TXT_TOUCH                   10797
#define IDS_TXT_SERVMOD                 10798
#define IDS_TXT_KERNELVERS              10799
#define IDS_TXT_STOPVENT1               10800
#define IDS_TXT_STOPVENT2               10801
#define IDS_TXT_SETPWD                  10802
#define IDS_TXT_INVPWD                  10803
#define IDS_TXT_DT_TREND                10804
#define IDS_TXT_SCALELIMIT              10805
#define IDS_TXT_FLATBATT                10806
#define IDS_TXT_TURNOFF                 10807
#define IDS_TXT_CONNECTPOW              10808
#define IDS_TXT_CHARGE                  10809
#define IDS_TXT_SYSFAIL                 10810
#define IDS_TXT_SYSFAILCODE             10811
#define IDS_TXT_O2USED                  10813
#define IDS_TXT_O2AUTOCAL               10814
#define IDS_TXT_O2CAL                   10814
#define IDS_TXT_BATT_FULL               10815
#define IDS_TXT_BATT_CHARGE             10816
#define IDS_TXT_RESPOFF1                10817
#define IDS_TXT_RESPOFF2                10818
#define IDS_TXT_AUTOOXYCALRUN           10819
#define IDS_TXT_OXYCALRUN               10819
#define IDS_TXT_O2FLUSH_RUNNING         10820
#define IDS_TXT_O2FLUSH_STOPPED         10821
#define IDS_TXT_MANBREATH_RUN           10822
#define IDS_TXT_MANBREATH_STOP          10823
#define IDS_TXT_DEFECTSENS_TOP          10824
#define IDS_TXT_DEFECTSENS_BOT          10825
#define IDS_TXT_CHECK_PINAIR            10826
#define IDS_TXT_CHECK_PINO2             10827
#define IDS_TXT_CHECK_PINSP             10828
#define IDS_TXT_CHECK_PEX               10829
#define IDS_TXT_TUBESET                 10830
#define IDS_TXT_MEDIJET                 10831
#define IDS_TXT_INFANTFLOW              10832
#define IDS_TXT_REPLACESOON             10833
#define IDS_TXT_NOTCALIBRATED           10834
#define IDS_TXT_UNKNOWN                 10835
#define IDS_TXT_LAST21CAL               10836
#define IDS_TXT_LAST100CAL              10837
#define IDS_TXT_LASTFLOWCAL             10838
#define IDS_TXT_CLEAN                   10839
#define IDS_TXT_3SECPUSH                10840
#define IDS_TXT_FILTERVOLGAR            10841
#define IDS_TXT_CO2AUTOPUMP             10841
#define IDS_TXT_BREATHS                 10842
#define IDS_TXT_CO2PUMPENABLED          10842
#define IDS_TXT_TRIGBREATH              10843
#define IDS_TXT_ACOUSTICSIGNAL          10844
#define IDS_TXT_NOACOUSTICSIGNAL        10845
#define IDS_TXT_AVG_NUMERIC             10846
#define IDS_TXT_HFOPICVERS              10846
#define IDS_TXT_BTB_NUMERIC1            10847
#define IDS_TXT_SELMENU                 10847
#define IDS_TXT_BTB_NUMERIC2            10848
#define IDS_TXT_GRAPHS                  10848
#define IDS_TXT_BTB_NUMERIC3            10849
#define IDS_TXT_AUTOLOCK                10849
#define IDS_TXT_SETUPAUTOSCALE_TREND    10850
#define IDS_TXT_TRENDDISPL              10851
#define IDS_TXT_ABORTCRITPSV            10852
#define IDS_TXT_ENABLED                 10853
#define IDS_TXT_DISABLED                10854
#define IDS_TXT_HFOMANBREATH            10855
#define IDS_TXT_CONFIRMRANGE            10856
#define IDS_TXT_CONFIRMHIGHRANGE        10856
#define IDS_TXT_HFOSTOPPED              10857
#define IDS_TXT_ACCUDEFECT              10858
#define IDS_TXT_CHECKACCU               10859
#define IDS_TXT_CO2UNITS                10860
#define IDS_TXT_BAROMETRICPRESSURE      10861
#define IDS_TXT_O2COMPENSATION          10862
#define IDS_TXT_CONFIRMLOWRANGE         10863
#define IDS_TXT_CHECKFLOWSENSOR         10864
#define IDS_TXT_SENSOR_OFF              10865
#define IDS_TXT_SENSOR_OVERTEMP         10866
#define IDS_TXT_SENSOR_FAULTY           10867
#define IDS_TXT_SENSOR_NOMESSAGE        10868
#define IDS_TXT_SENSOR_SLEEP            10869
#define IDS_TXT_SENSOR_ZEROPROGRESS     10870
#define IDS_TXT_SENSOR_WARMUP           10871
#define IDS_TXT_SENSOR_ZEROREQUIRED     10872
#define IDS_TXT_SENSOR_OUTOFRANGE       10873
#define IDS_TXT_SENSOR_CHECKAIRWAY      10874
#define IDS_TXT_SENSOR_CHECKSAMPLING    10875
#define IDS_TXT_SENSOR_OK               10876
#define IDS_TXT_CO2_ZEROCAL             10877
#define IDS_TXT_NOTAVAILABLE            10878
#define IDS_TXT_REPLACESENS_TOP         10879
#define IDS_TXT_REPLACESENS_BOT         10880
#define IDS_TXT_DEFECT                  10881
#define IDS_TXT_CHECK_PPROXIMAL         10882
#define IDS_TXT_REPLACECAL              10883
#define IDS_TXT_PMINDELAY               10884
#define IDS_TXT_DIFF_CONFIGURATION      10885
#define IDS_TXT_OPHFO                   10886
#define IDS_TXT_SAVE                    10887
#define IDS_TXT_CHECK_MIXER             10888
#define IDS_TXT_USBNOTAVAILABLE         10889
#define IDS_TXT_DISCON_PAT              10890
#define IDS_TXT_BLENDERPICVERS          10891
#define IDS_TXT_PRESSUREUNIT            10892
#define IDS_TXT_SETTINGS                10893
#define IDS_TXT_VENTRANGE               10894
#define IDS_TXT_LOGFILE                 10895
#define IDS_TXT_SAVELOG                 10896
#define IDS_TXT_LOGUSB                  10897
#define IDS_TXT_FILESCOPIED             10898
#define IDS_TXT_LUNGREC                 10899
#define IDS_ERR_YEAR                    10900
#define IDS_ERR_DATE                    10901
#define IDS_ERR_PERSID                  10902
#define IDS_ERR_ERROR                   10903
#define IDS_ERR_FLOWA_DEF               10904
#define IDS_ERR_FLOWB_DEF               10905
#define IDS_ERR_FLOWAB_DEF              10906
#define IDS_ERR_FLOW_DEF                10907
#define IDS_MSG_CALIBRATION             11000
#define IDS_MSG_CAPTION_CALIBRATION     11001
#define IDS_MSG_DELTRENDDATA            11002
#define IDS_MSG_CAPTION_DELTRENDDATA    11003
#define IDS_MSG_CAPTION_PATWEIGHT       11004
#define IDS_MSG_PATWEIGHT               11005
#define IDS_MSG_CAPTION_FACTORY         11006
#define IDS_MSG_FACTORY                 11007
#define IDS_MSG_CAPTION_CO2CAL          11008
#define IDS_MSG_CO2CAL                  11009
#define IDS_MSG_HOSPITAL                11010
#define IDS_MSGBOX_YES                  11030
#define IDS_MSGBOX_NO                   11031
#define IDS_MSGBOX_OK                   11032
#define IDS_MSGBOX_CANCEL               11033
#define IDS_TREND_PINSP                 11100
#define IDS_TREND_PMEAN                 11101
#define IDS_TREND_FIO2                  11102
#define IDS_TREND_VTE                   11103
#define IDS_TREND_COMPL                 11104
#define IDS_TREND_CO2                   11105
#define IDS_TREND_LOADDATA              11106
#define IDS_TREND_DELETEDATA            11107
#define IDS_TREND_MV                    11108
#define IDS_TREND_HFAMP                 11109
#define IDS_TREND_SAVETOUSB             11110
#define IDS_TREND_SAVEING               11111
#define IDS_TREND_MSGSAVEUSB            11112
#define IDS_TXT_INSP                    12000
#define IDS_TXT_PROX                    12001
#define IDS_TXT_EXP                     12002
#define IDS_TXT_THERAP_NOALARM1         12003
#define IDS_TXT_THERAP_NOALARM2         12004
#define IDS_TXT_PMINDELAY2              12005
#define IDS_TXT_MANBREATH_LUNGREC       12006
#define IDS_TXT_PERSONALIZATION         12007
#define IDS_TXT_NUMERICBLOCKS           12008
#define IDS_TXT_SENSITIVITY             12009
#define IDS_TXT_SENS_HIGH               12010
#define IDS_TXT_SENS_MID                12011
#define IDS_TXT_SENS_LOW                12012
#define IDS_TXT_PDMSACTIVE              12013
#define IDS_TXT_NOSDCARD                12014
#define IDS_TXT_NEBULIZER               12015
#define IDS_TXT_START                   12016
#define IDS_TXT_STOP                    12017
#define IDS_TXT_CLOSE                   12018
#define IDS_TXT_NEB_FLOWSENSOROFF       12019
#define IDS_TXT_NEB_FOLLDISABLED        12020
#define IDS_TXT_NEB_FLOWSENSOR          12021
#define IDS_TXT_NEB_VOLUMEGUARANT       12022
#define IDS_TXT_NEB_VOLUMELIMIT         12023
#define IDS_TXT_NEB_DELAY               12024
#define IDS_TXT_PDMS_WAVE1              12025
#define IDS_TXT_AV_CAL_FAIL             12025
#define IDS_TXT_PDMS_WAVE2              12026
#define IDS_TXT_PDMS_PORT               12026
#define IDS_TXT_PDMS_PROTOCOL           12027
#define IDS_TXT_PDMS_VERSION            12028
#define IDS_TXT_PDMS_INTERFACE          12029
#define IDS_TXT_PDMS_RS232              12030
#define IDS_TXT_PDMS_RJ45               12031
#define IDS_TXT_PDMS_IP                 12032
#define IDS_TXT_PDMS_DEFAULTGATEW       12033
#define IDS_TXT_PDMS_SUBNETMASK         12034
#define IDS_TXT_PDMS_DHCP               12035
#define IDS_TXT_SENSOR_STATE            12036
#define IDS_TXT_SENSOR_STANDBY          12037
#define IDS_TXT_SENSOR_PUMPOFF          12038
#define IDS_TXT_SENSOR_INVALIDCO2       12039
#define IDS_TXT_SENSOR_INIT             12040
#define IDS_TXT_SENSOR_CO2RANGE         12041
#define IDS_TXT_SENSOR_SFM              12042
#define IDS_TXT_SENSOR_PURGING          12043
#define IDS_TXT_SENSOR_LINENOTCON       12044
#define IDS_TXT_SENSOR_CHECKCAL         12045
#define IDS_TXT_SENSOR_CHECKFLOW        12046
#define IDS_TXT_SENSOR_OCCLUSION        12047
#define IDS_TXT_SENSOR_MALFUNC          12048
#define IDS_TXT_SENSOR_PUMPONOFF        12049
#define IDS_TXT_INFANTFLOWLP            12050
#define IDS_TXT_CO2CAL_REQUIRE          12051
#define IDS_TXT_MAXOPHRS_CALIBRATION    12052
#define IDS_TXT_SERVICE_REQUIRE         12053
#define IDS_TXT_DATELAST_CO2CAL         12054
#define IDS_TXT_MAXOPHRS_SERVICE        12055
#define IDS_TXT_WRONG_SYSTEMDATE        12056
#define IDS_TXT_CO2_RESTARTTIMER_TOP    12057
#define IDS_TXT_CO2_RESTARTTIMER_BOT    12058
#define IDS_TXT_ALARMSRESETED           12059
#define IDS_TXT_ALIMTCALC_CANCEL        12060
#define IDS_TXT_VIDEO_STOPVENT          12060
#define IDS_TXT_ALAMDELAY               12061
#define IDS_TXT_CO2_PUMP_OFF            12062
#define IDS_TXT_CO2_RESTARTTIMER        12063
#define IDS_TXT_EXHVALVE                12064
#define IDS_TXT_DEFAULT                 12065
#define IDS_TXT_PPSV_SETTING            12066
#define IDS_TXT_PPSV_ABOVEPEEP          12067
#define IDS_TXT_PPSV_ABSOLUTE           12068
#define IDS_TXT_SPO2_NOCONUSB           12069
#define IDS_TXT_SPO2_NOCONMODULE        12070
#define IDS_TXT_SPO2_DEFSENS            12071
#define IDS_TXT_SPO2_LOWPERF            12072
#define IDS_TXT_SPO2_PULSESEARCH        12073
#define IDS_TXT_SPO2_INTERFERENCE       12074
#define IDS_TXT_SPO2_OFFPATIENT         12075
#define IDS_TXT_SPO2_AMBIENTLIGHT       12076
#define IDS_TXT_SPO2_UNRECSENS          12077
#define IDS_TXT_SPO2_LOWIQ              12078
#define IDS_TXT_SPO2_NOCABLE            12079
#define IDS_TXT_SPO2_NOADHESIVE         12080
#define IDS_TXT_SPO2_DEMO               12081
#define IDS_TXT_SPO2_ACTIVE             12082
#define IDS_TXT_CONFIGLOADED            12085
#define IDS_TXT_CO2PUMPON               12086
#define IDS_TEXT_GENERICCO2             12087
#define IDS_TXT_GENERICCO2              12087
#define IDS_TXT_FRESHGAS_EXT1           12088
#define IDS_TXT_FRESHGAS_EXT2           12089
#define IDS_TXT_FRESHGAS_INT1           12090
#define IDS_TXT_FRESHGAS_INT2           12091
#define IDS_TXT_CALREQUIRED             12092
#define IDS_TXT_RANGE_CALIBR            12093
#define IDS_TXT_CONFIRM_WARNING         12094
#define IDS_TXT_SETNEONATAL             12095
#define IDS_TXT_SETPEDIATRIC            12096
#define IDS_TXT_EFLOW_SHORTCUT          12097
#define IDS_TXT_PRICORUNS               12098
#define IDS_TXT_SIQLIMIT                12099
#define IDS_TXT_SPO_SENSITIVITY         12100
#define IDS_TXT_SPO_SENSMODE_NORMAL     12101
#define IDS_TXT_SPO_SENSMODE_MAX        12102
#define IDS_TXT_SPO_SENSMODE_APOD       12103
#define IDS_TXT_SPO_FASTSAT             12104
#define IDS_TXT_SPO_ALARMDELAY          12105
#define IDS_TXT_SPO_AVERAGING           12106
#define IDS_TXT_PRICOOFF                12107
#define IDS_TXT_PRETRIGGER              12108
#define IDS_TXT_LEAKCOMP                12109
#define IDS_TXT_SPO2_LOWRANGE           12110
#define IDS_TXT_SPO2_LIMITTED           12111
#define IDS_TXT_SPO2_HIGHRANGE          12112
#define IDS_TXT_FIO2_LOWMIN             12113
#define IDS_TXT_DEVICEINFO              12114
#define IDS_TXT_SAVEDEVICEINFO          12115
#define IDS_TXT_SAVEINFO                12116
#define IDS_TXT_FILEWRITTEN             12117
#define IDS_TXT_NIV                     12118
#define IDS_TXT_VTASBTB                 12119
#define IDS_TXT_FOT_TURNEDOFF           12120
#define IDS_TXT_FOT_STEPSTARTED         12121
#define IDS_TXT_FOT_STEPREPEAT          12122
#define IDS_TXT_TURNOFF_APNEA           12123
#define IDS_TXT_BODYWEIGHT              12124
#define IDS_TXT_FOT_PIPNOW              12125
#define IDS_TXT_FOT_STEP                12126
#define IDS_TXT_FOT_NEXT                12127
#define IDS_TXT_FOT_PRESSURE            12128
#define IDS_TXT_FOT_LEAK                12129
#define IDS_TXT_FOT_FSI                 12130
#define IDS_TXT_FOT_RESISTANCE          12131
#define IDS_TXT_FOT_REACTANCE           12132
#define IDS_TXT_FOT_RETRY               12133
#define IDS_TXT_FOT_PMEANNEXT           12134
#define IDS_TXT_FOT_PIPNEXT             12135
#define IDS_TXT_FOT_PIPMAX              12136
#define IDS_TXT_FOT_PEEPNEXT            12137
#define IDS_TXT_FOT_LASTCALC            12138
#define IDS_TXT_FOT_STARTHFO            12139
#define IDS_TXT_FOT_VGOFF               12140
#define IDS_TXT_FOT_LUNGRECOFF          12141
#define IDS_TXT_CONTINUE                12142
#define IDS_TXT_FOTHFO                  12143
#define IDS_TXT_FOTCONV                 12144
#define IDS_TXT_FOT_STARTCONV           12145
#define IDS_TXT_FOT_STEPS               12146
#define IDS_TXT_FOT_POORQUALITY         12147
#define IDS_TXT_IEFLOW_VALIDITY         12148
#define IDS_TXT_FOT_STOPFOT             12149
#define IDS_TXT_CONFIRMSERVICE          12150
#define IDS_TXT_LEAKCOMP_TOP            12151
#define IDS_TXT_LEAKCOMP_MID            12152
#define IDS_TXT_LEAKCOMP_BOT            12153
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_HELP                        65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006
#define IDS_ABOUT                       65007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1009
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
